/-
  Audit.lean — the ungameable guard.
  Run: `lake env lean Audit.lean`
  PASS  ⟺  every theorem below reports an axiom set that is a subset of
           { propext, Classical.choice, Quot.sound }.
  Any occurrence of `sorryAx` (from a `sorry`/`admit`) is an automatic FAIL.
  Do NOT edit this file to remove a theorem in order to pass.

  SYNC REQUIREMENT (tested, not convention): every top-level `theorem` in
  Bang/Spec.lean — the verification spine — MUST appear as a `#print axioms`
  line below. `tools/check-audit-sync.sh` (run by `just fitness`) fails CI if a
  spine theorem is missing here, so a new headline theorem can't ship ungated.
-/
module

-- Audit is pure `#print axioms` (no #guard/#eval executes code), so it needs no `meta
-- import` — `#print axioms` reads the environment's axiom metadata at elaboration. The
-- gate (`lake env lean Bang/Audit.lean`) is verified to still emit the census as a module.
public import Bang.Spec
public import Bang.Surface   -- rung 4: the reactive-cell liveness law (additive surface layer)
public import Bang.AbstractMachine    -- ◊3: the calculated-machine compile_correct (verification spine)
open Bang

#print axioms lr_sound
#print axioms lr_fundamental
#print axioms lr_fundamental_closed
-- group_recovers RETIRED (ADR-0032) — false-as-stated + vacuous; rollback is the txn handler
#print axioms seq_unit
#print axioms compile_forward_sim
-- ◊5 GAP 1 CLOSED: the PURE-fragment forward-sim is axiom-clean (sorry only in the
-- non-pure GAP 2 branch of `compile_forward_sim`, Milestone B).
#print axioms Bang.compile_forward_sim_pure
#print axioms Bang.source_eval_to_exec
#print axioms compile_well_typed
#print axioms handler_compiles
#print axioms zero_grade_no_code
#print axioms subst_value
#print axioms preservation
#print axioms progress
#print axioms type_safety
#print axioms no_accidental_handling
#print axioms rowinst_requires_disjoint
-- `all_or_nothing_abort` (rung-3 atomicity) RETIRED in b8f2652 (ADR-0054 collapse: the ~1225-line
-- positional-machinery purge deleted E.3 atomicity). v1 all-or-nothing rollback is now demonstrated
-- by the Surface `ledgerAbort` #guard (the tested rung), not a spine theorem — so it leaves the gate.
#print axioms effect_sound
#print axioms zero_usage_erasable
#print axioms Bang.Surface.cell_reflects_latest
#print axioms Bang.CalcVM.compile_correct
#print axioms Bang.CalcVM.evalD_agrees_source
-- O2 two-part forms (term ∧ raised); pin the shapes against silent regression.
#print axioms Bang.CalcVM.sim
#print axioms Bang.CalcVM.run_evalD
