module

-- Audit is pure `#print axioms` (no #guard/#eval executes code), so it needs no `meta
-- import` — `#print axioms` reads the environment's axiom metadata at elaboration. The
-- gate (`lake env lean Bang/Audit.lean`) is verified to still emit the census as a module.
public import Bang.Spec
public import Bang.Frontend.Surface   -- rung 4: the reactive-cell liveness law (additive surface layer)
public import Bang.Backend.AbstractMachine    -- ◊3: the calculated-machine compile_correct (verification spine)
public import Bang.Backend.Rung5ProofGrade    -- rung-5 S5: the effectful-obligation re-exports (durable axiom pin)
public import Bang.Backend.EnvMachine          -- default engine: environment-to-evalD correspondence
public import Bang.Distribution.LatticeStore   -- CALM floor: the join-only replicated-store laws

/-!
  Audit.lean — the headline-theorem axiom census.
  Run: `just axioms`, which evaluates this census and compares it exactly with
  the committed machine-readable baseline in `docfacts/proof.json` via
  `tools/docfacts_proof.py --live-check`.

  The raw `lake env lean Bang/Audit.lean` command is observational: it prints
  dependencies but does not fail merely because `sorryAx` appears. The wrapper
  is the fail-closed baseline gate: every enrollment and axiom set must match
  the reviewed proof fact exactly, so a missing report, new `sorryAx`, or any
  other dependency change fails mechanically until explicitly regenerated and
  reviewed. A separate trusted-three census remains visible in the output.
  Do NOT edit this file to remove a theorem in order to pass.

  SYNC REQUIREMENT (tested, not convention): every top-level `theorem` in
  Bang/Spec.lean — the verification spine — MUST appear as a `#print axioms`
  line below. `tools/check-audit-sync.sh` (run by `just fitness`) fails CI if a
  spine theorem is missing here, so a new headline theorem can't ship ungated.
-/

open Bang

#print axioms lr_sound
#print axioms lr_fundamental
#print axioms lr_fundamental_closed
-- group_recovers RETIRED (ADR-0032) — false-as-stated + vacuous; rollback is the txn handler
#print axioms seq_unit
#print axioms compile_forward_sim
-- ◊5 GAP 1 CLOSED: the PURE-fragment forward-sim is axiom-clean (sorry only in the
-- non-pure GAP 2 branch of `compile_forward_sim`, Milestone B).
#print axioms Bang.compile_forward_sim_pure
#print axioms Bang.source_eval_to_exec
-- rung-5 S5 (durable pin): the effectful `wexec ≡ Source.eval` obligation re-exported under the
-- S5 name. `s5_effectful_forward_sim` = `compile_forward_sim` (trusted-3); `s5_exec_wexec_lockstep`
-- = `exec_wexec_sim_ok` ([propext, Quot.sound]). Gating them here means the CustomFree-drop /
-- whole-v1-effect-set coverage can't silently regress. (The `$env`-slot↔store GC-bijection half is
-- UNSTATEABLE in v1 — no GC machine to state against — so it has no theorem to enrol; see
-- `docs/notes/rung5-s5-proofgrade-refutation.md`.)
#print axioms Bang.Rung5ProofGrade.s5_effectful_forward_sim
#print axioms Bang.Rung5ProofGrade.s5_exec_wexec_lockstep
#print axioms compileC_satisfies_current_instrWF
#print axioms compile_well_typed
#print axioms handler_lowering_placeholder
#print axioms handler_compiles
#print axioms compileC_emits_no_locals
#print axioms zero_grade_no_code
#print axioms subst_value
#print axioms preservation
#print axioms progress
#print axioms type_safety
#print axioms no_accidental_handling
-- #44 STAGE 6 (ADR-0085) — user-effect soundness composition. Both ⊆ trusted-three (custom_program_safe
-- rides type_safety; no_accidental_handling_custom rides the axiom-free no_accidental_handling).
#print axioms no_accidental_handling_custom
#print axioms closed_fully_handled_program_no_unclassified_stuck
#print axioms custom_program_safe
#print axioms rowinst_requires_disjoint
-- `all_or_nothing_abort` (rung-3 atomicity) RETIRED in b8f2652 (ADR-0054 collapse: the ~1225-line
-- positional-machinery purge deleted E.3 atomicity). v1 all-or-nothing rollback is now demonstrated
-- by the Surface `ledgerAbort` #guard (the tested rung), not a spine theorem — so it leaves the gate.
#print axioms evalTrace_dispatches_within_recorded_live_bound
#print axioms effect_sound
#print axioms zero_usage_erasable
#print axioms Bang.Surface.cell_reflects_latest
#print axioms Bang.CalcVM.compile_correct
#print axioms Bang.CalcVM.evalD_agrees_source
-- O2 two-part forms (term ∧ raised); pin the shapes against silent regression.
#print axioms Bang.CalcVM.sim
#print axioms Bang.CalcVM.run_evalD
#print axioms Bang.EnvMachine.evalE_agrees_evalD
-- Join-only distributed-state floor. These five claims are product-facing proof assets, so enroll
-- them in the fail-closed baseline rather than merely printing them from their leaf module.
#print axioms Bang.Distribution.LatticeStore.le_join
#print axioms Bang.Distribution.LatticeStore.join_commutes
#print axioms Bang.Distribution.LatticeStore.join_idempotent
#print axioms Bang.Distribution.LatticeStore.pair_converges_after_exchange
#print axioms Bang.Distribution.LatticeStore.updates_are_join_only
