/-
  Audit.lean — the ungameable guard.
  Run: `lake env lean Audit.lean`
  PASS  ⟺  every theorem below reports an axiom set that is a subset of
           { propext, Classical.choice, Quot.sound }.
  Any occurrence of `sorryAx` (from a `sorry`/`admit`) is an automatic FAIL.
  Do NOT edit this file to remove a theorem in order to pass.

  SYNC REQUIREMENT (tested, not convention): every top-level `theorem` in
  Bang/Spec.lean — the verification spine — MUST appear as a `#print axioms`
  line below. `tools/check-audit-sync.sh` (run by `just fitness`) fails CI if a
  spine theorem is missing here, so a new headline theorem can't ship ungated.
-/
import Bang.Spec
import Bang.Surface   -- rung 4: the reactive-cell liveness law (additive surface layer)
import Bang.CalcVM    -- ◊3: the calculated-machine compile_correct (verification spine)
import Bang.CapLabelCohRefute  -- inc-6 U3: route-B do-not-weaken refutation witness
open Bang

#print axioms lr_sound
#print axioms lr_fundamental
#print axioms lr_fundamental_closed
-- group_recovers RETIRED (ADR-0032) — false-as-stated + vacuous; rollback is the txn handler
#print axioms seq_unit
#print axioms compile_forward_sim
-- ◊5 GAP 1 CLOSED: the PURE-fragment forward-sim is axiom-clean (sorry only in the
-- non-pure GAP 2 branch of `compile_forward_sim`, Milestone B).
#print axioms Bang.compile_forward_sim_pure
#print axioms Bang.source_eval_to_exec
#print axioms compile_well_typed
#print axioms handler_compiles
#print axioms zero_grade_no_code
#print axioms subst_value
#print axioms preservation
#print axioms progress
#print axioms type_safety
#print axioms no_accidental_handling
#print axioms rowinst_requires_disjoint
#print axioms all_or_nothing_abort
#print axioms effect_sound
#print axioms zero_usage_erasable
#print axioms Bang.Surface.cell_reflects_latest
#print axioms Bang.CalcVM.compile_correct
#print axioms Bang.CalcVM.evalD_agrees_source
-- O2 two-part forms (term ∧ raised); pin the shapes against silent regression.
#print axioms Bang.CalcVM.sim
#print axioms Bang.CalcVM.run_evalD
-- inc-6 U3 route-B REFUTATION WITNESS (do-not-weaken): a state frame present at identity 0
-- does NOT give `CapResolves` at the cap's label 2 — pins WHY `run_evalD`'s perform-term arm
-- needs the cap-label-coherence premise (evalD dispatches by identity, kernel fail-louds on label).
#print axioms refute_frame_present_but_no_capResolves
