(module
  (rec
    (type $val  (sub (struct)))
    (type $ival (sub $val (struct (field i64))))
    (type $limbs  (array (mut i64)))
    (type $bigval (sub $val (struct (field $sign i32) (field $mag (ref $limbs)))))
    (type $sum  (sub $val (struct (field $tag i32) (field $payload (ref null $val)))))
    (type $pair (sub $val (struct (field (ref null $val)) (field (ref null $val)))))
    (type $ref  (sub $val (struct (field (mut (ref null $val))))))
    (type $txbox (sub $val (struct (field (mut (ref null $env))))))
    (type $env  (struct (field $hd (ref null $val)) (field $tl (ref null $env))))
    (type $fn   (func (param (ref null $env)) (param (ref null $val)) (result (ref null $val))))
    (type $clos (sub $val (struct (field $code (ref $fn)) (field $env (ref null $env))))))
    (import "wasi_snapshot_preview1" "fd_write"
    (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $cur (mut i32) (i32.const 16))
  (data (i32.const 0) "()inl inr <thunk>")
    (func $box (param $n i64) (result (ref null $val)) (struct.new $ival (local.get $n)))
  (func $lookup (param $e (ref null $env)) (param $n i32) (result (ref null $val))
    (block $done (loop $l
      (br_if $done (i32.eqz (local.get $n)))
      (local.set $e (struct.get $env $tl (local.get $e)))
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br $l)))
    (struct.get $env $hd (local.get $e)))
  (func $txlen (param $h (ref null $env)) (result i64) (local $n i64)
    (local.set $n (i64.const 0))
    (block $d (loop $l
      (br_if $d (ref.is_null (local.get $h)))
      (local.set $n (i64.add (local.get $n) (i64.const 1)))
      (local.set $h (struct.get $env $tl (local.get $h)))
      (br $l)))
    (local.get $n))
  (func $txcell (param $h (ref null $env)) (param $i i64) (result (ref $ref)) (local $k i64)
    (local.set $k (i64.sub (i64.sub (call $txlen (local.get $h)) (i64.const 1)) (local.get $i)))
    (block $d (loop $l
      (br_if $d (i64.eqz (local.get $k)))
      (local.set $h (struct.get $env $tl (local.get $h)))
      (local.set $k (i64.sub (local.get $k) (i64.const 1)))
      (br $l)))
    (ref.cast (ref $ref) (struct.get $env $hd (local.get $h))))
  (func $clausecell (param $h (ref null $env)) (param $k i64) (result (ref null $val))
    (block $d (loop $l
      (br_if $d (i64.eqz (local.get $k)))
      (local.set $h (struct.get $env $tl (local.get $h)))
      (local.set $k (i64.sub (local.get $k) (i64.const 1)))
      (br $l)))
    (struct.get $env $hd (local.get $h)))
    (func $bIsBig (param $v (ref null $val)) (result i32) (ref.test (ref $bigval) (local.get $v)))
  (func $bIsIval (param $v (ref null $val)) (result i32) (ref.test (ref $ival) (local.get $v)))
  (func $bIvalN (param $v (ref null $val)) (result i64) (struct.get $ival 0 (ref.cast (ref $ival) (local.get $v))))
  (func $bLimbsOfU (param $m i64) (result (ref $limbs)) (local $n i32) (local $t i64) (local $r (ref $limbs)) (local $i i32)
    (local.set $n (i32.const 1)) (local.set $t (i64.div_u (local.get $m) (i64.const 1000000000)))
    (block $cd (loop $cl (br_if $cd (i64.eqz (local.get $t)))
      (local.set $n (i32.add (local.get $n) (i32.const 1)))
      (local.set $t (i64.div_u (local.get $t) (i64.const 1000000000))) (br $cl)))
    (local.set $r (array.new_default $limbs (local.get $n))) (local.set $i (i32.const 0))
    (block $d (loop $l (br_if $d (i32.ge_u (local.get $i) (local.get $n)))
      (array.set $limbs (local.get $r) (local.get $i) (i64.rem_u (local.get $m) (i64.const 1000000000)))
      (local.set $m (i64.div_u (local.get $m) (i64.const 1000000000)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
    (local.get $r))
  (func $bToBig (param $v (ref null $val)) (result (ref $bigval)) (local $n i64) (local $sign i32) (local $mag i64)
    (if (result (ref $bigval)) (call $bIsBig (local.get $v))
      (then (ref.cast (ref $bigval) (local.get $v)))
      (else
        (local.set $n (call $bIvalN (local.get $v)))
        (if (i64.lt_s (local.get $n) (i64.const 0))
          (then (local.set $sign (i32.const 1)) (local.set $mag (i64.sub (i64.const 0) (local.get $n))))
          (else (local.set $sign (i32.const 0)) (local.set $mag (local.get $n))))
        (struct.new $bigval (local.get $sign) (call $bLimbsOfU (local.get $mag))))))
  (func $bAddMag (param $a (ref $limbs)) (param $b (ref $limbs)) (result (ref $limbs))
    (local $la i32) (local $lb i32) (local $n i32) (local $i i32) (local $carry i64) (local $sum i64) (local $r (ref $limbs)) (local $av i64) (local $bv i64)
    (local.set $la (array.len (local.get $a))) (local.set $lb (array.len (local.get $b)))
    (local.set $n (i32.add (select (local.get $la) (local.get $lb) (i32.gt_u (local.get $la) (local.get $lb))) (i32.const 1)))
    (local.set $r (array.new_default $limbs (local.get $n))) (local.set $i (i32.const 0)) (local.set $carry (i64.const 0))
    (block $d (loop $l (br_if $d (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $av (if (result i64) (i32.lt_u (local.get $i) (local.get $la)) (then (array.get $limbs (local.get $a) (local.get $i))) (else (i64.const 0))))
      (local.set $bv (if (result i64) (i32.lt_u (local.get $i) (local.get $lb)) (then (array.get $limbs (local.get $b) (local.get $i))) (else (i64.const 0))))
      (local.set $sum (i64.add (i64.add (local.get $av) (local.get $bv)) (local.get $carry)))
      (local.set $carry (i64.div_u (local.get $sum) (i64.const 1000000000)))
      (array.set $limbs (local.get $r) (local.get $i) (i64.rem_u (local.get $sum) (i64.const 1000000000)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
    (call $bTrim (local.get $r)))
  (func $bCmpMag (param $a (ref $limbs)) (param $b (ref $limbs)) (result i32)
    (local $la i32) (local $lb i32) (local $i i32) (local $av i64) (local $bv i64)
    (local.set $la (array.len (local.get $a))) (local.set $lb (array.len (local.get $b)))
    (if (i32.gt_u (local.get $la) (local.get $lb)) (then (return (i32.const 1))))
    (if (i32.lt_u (local.get $la) (local.get $lb)) (then (return (i32.const -1))))
    (local.set $i (i32.sub (local.get $la) (i32.const 1)))
    (block $d (loop $l (br_if $d (i32.lt_s (local.get $i) (i32.const 0)))
      (local.set $av (array.get $limbs (local.get $a) (local.get $i))) (local.set $bv (array.get $limbs (local.get $b) (local.get $i)))
      (if (i64.gt_u (local.get $av) (local.get $bv)) (then (return (i32.const 1))))
      (if (i64.lt_u (local.get $av) (local.get $bv)) (then (return (i32.const -1))))
      (local.set $i (i32.sub (local.get $i) (i32.const 1))) (br $l)))
    (i32.const 0))
  (func $bTrim (param $r (ref $limbs)) (result (ref $limbs)) (local $top i32) (local $n i32) (local $i i32) (local $o (ref $limbs))
    (local.set $top (i32.sub (array.len (local.get $r)) (i32.const 1)))
    (block $td (loop $tl (br_if $td (i32.eqz (local.get $top)))
      (br_if $td (i64.ne (array.get $limbs (local.get $r) (local.get $top)) (i64.const 0)))
      (local.set $top (i32.sub (local.get $top) (i32.const 1))) (br $tl)))
    (local.set $n (i32.add (local.get $top) (i32.const 1)))
    (if (i32.eq (local.get $n) (array.len (local.get $r))) (then (return (local.get $r))))
    (local.set $o (array.new_default $limbs (local.get $n))) (local.set $i (i32.const 0))
    (block $cd (loop $cl (br_if $cd (i32.ge_u (local.get $i) (local.get $n)))
      (array.set $limbs (local.get $o) (local.get $i) (array.get $limbs (local.get $r) (local.get $i)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $cl)))
    (local.get $o))
  (func $bSubMag (param $a (ref $limbs)) (param $b (ref $limbs)) (result (ref $limbs))
    (local $la i32) (local $lb i32) (local $i i32) (local $borrow i64) (local $av i64) (local $bv i64) (local $diff i64) (local $r (ref $limbs))
    (local.set $la (array.len (local.get $a))) (local.set $lb (array.len (local.get $b)))
    (local.set $r (array.new_default $limbs (local.get $la))) (local.set $i (i32.const 0)) (local.set $borrow (i64.const 0))
    (block $d (loop $l (br_if $d (i32.ge_u (local.get $i) (local.get $la)))
      (local.set $av (array.get $limbs (local.get $a) (local.get $i)))
      (local.set $bv (if (result i64) (i32.lt_u (local.get $i) (local.get $lb)) (then (array.get $limbs (local.get $b) (local.get $i))) (else (i64.const 0))))
      (local.set $diff (i64.sub (i64.sub (local.get $av) (local.get $bv)) (local.get $borrow)))
      (if (i64.lt_s (local.get $diff) (i64.const 0))
        (then (local.set $diff (i64.add (local.get $diff) (i64.const 1000000000))) (local.set $borrow (i64.const 1)))
        (else (local.set $borrow (i64.const 0))))
      (array.set $limbs (local.get $r) (local.get $i) (local.get $diff))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
    (call $bTrim (local.get $r)))
  (func $bNormBig (param $sign i32) (param $mag (ref $limbs)) (result (ref null $val)) (local $len i32) (local $v i64)
    (local.set $len (array.len (local.get $mag)))
    (if (i32.le_u (local.get $len) (i32.const 2))
      (then
        (local.set $v (array.get $limbs (local.get $mag) (i32.const 0)))
        (if (i32.eq (local.get $len) (i32.const 2))
          (then (local.set $v (i64.add (local.get $v) (i64.mul (array.get $limbs (local.get $mag) (i32.const 1)) (i64.const 1000000000))))))
        (if (i32.eq (local.get $sign) (i32.const 1)) (then (local.set $v (i64.sub (i64.const 0) (local.get $v)))))
        (return (struct.new $ival (local.get $v)))))
    (struct.new $bigval (local.get $sign) (local.get $mag)))
  (func $addVal (param $x (ref null $val)) (param $y (ref null $val)) (result (ref null $val))
    (local $bx (ref $bigval)) (local $by (ref $bigval)) (local $sx i32) (local $sy i32) (local $mx (ref $limbs)) (local $my (ref $limbs)) (local $c i32) (local $a i64) (local $b i64) (local $s i64)
    (if (i32.and (call $bIsIval (local.get $x)) (call $bIsIval (local.get $y)))
      (then
        (local.set $a (call $bIvalN (local.get $x))) (local.set $b (call $bIvalN (local.get $y)))
        (local.set $s (i64.add (local.get $a) (local.get $b)))
        (if (i64.ge_s (i64.and (i64.xor (local.get $a) (local.get $s)) (i64.xor (local.get $b) (local.get $s))) (i64.const 0))
          (then (return (struct.new $ival (local.get $s)))))))
    (local.set $bx (call $bToBig (local.get $x))) (local.set $by (call $bToBig (local.get $y)))
    (local.set $sx (struct.get $bigval $sign (local.get $bx))) (local.set $sy (struct.get $bigval $sign (local.get $by)))
    (local.set $mx (struct.get $bigval $mag (local.get $bx))) (local.set $my (struct.get $bigval $mag (local.get $by)))
    (if (result (ref null $val)) (i32.eq (local.get $sx) (local.get $sy))
      (then (call $bNormBig (local.get $sx) (call $bAddMag (local.get $mx) (local.get $my))))
      (else
        (local.set $c (call $bCmpMag (local.get $mx) (local.get $my)))
        (if (result (ref null $val)) (i32.eqz (local.get $c))
          (then (struct.new $ival (i64.const 0)))
          (else (if (result (ref null $val)) (i32.eq (local.get $c) (i32.const 1))
            (then (call $bNormBig (local.get $sx) (call $bSubMag (local.get $mx) (local.get $my))))
            (else (call $bNormBig (local.get $sy) (call $bSubMag (local.get $my) (local.get $mx))))))))))
  (func $bNeg (param $v (ref null $val)) (result (ref null $val)) (local $bg (ref $bigval)) (local $n i64)
    (if (result (ref null $val)) (call $bIsIval (local.get $v))
      (then
        (local.set $n (call $bIvalN (local.get $v)))
        (if (result (ref null $val)) (i64.eq (local.get $n) (i64.const -9223372036854775808))
          (then (struct.new $bigval (i32.const 0) (call $bLimbsOfU (i64.const 9223372036854775808))))
          (else (struct.new $ival (i64.sub (i64.const 0) (local.get $n))))))
      (else
        (local.set $bg (ref.cast (ref $bigval) (local.get $v)))
        (if (result (ref null $val)) (i32.and (i32.eq (array.len (struct.get $bigval $mag (local.get $bg))) (i32.const 1)) (i64.eqz (array.get $limbs (struct.get $bigval $mag (local.get $bg)) (i32.const 0))))
          (then (local.get $v))
          (else (struct.new $bigval (i32.xor (struct.get $bigval $sign (local.get $bg)) (i32.const 1)) (struct.get $bigval $mag (local.get $bg))))))))
  (func $subVal (param $x (ref null $val)) (param $y (ref null $val)) (result (ref null $val))
    (call $addVal (local.get $x) (call $bNeg (local.get $y))))
  (func $cmpVal (param $x (ref null $val)) (param $y (ref null $val)) (result i32)
    (local $bx (ref $bigval)) (local $by (ref $bigval)) (local $sx i32) (local $sy i32) (local $c i32) (local $a i64) (local $b i64)
    (if (i32.and (call $bIsIval (local.get $x)) (call $bIsIval (local.get $y)))
      (then
        (local.set $a (call $bIvalN (local.get $x))) (local.set $b (call $bIvalN (local.get $y)))
        (if (i64.lt_s (local.get $a) (local.get $b)) (then (return (i32.const -1))))
        (if (i64.gt_s (local.get $a) (local.get $b)) (then (return (i32.const 1))))
        (return (i32.const 0))))
    (local.set $bx (call $bToBig (local.get $x))) (local.set $by (call $bToBig (local.get $y)))
    (local.set $sx (struct.get $bigval $sign (local.get $bx))) (local.set $sy (struct.get $bigval $sign (local.get $by)))
    (if (i32.ne (local.get $sx) (local.get $sy)) (then (return (select (i32.const -1) (i32.const 1) (i32.eq (local.get $sx) (i32.const 1))))))
    (local.set $c (call $bCmpMag (struct.get $bigval $mag (local.get $bx)) (struct.get $bigval $mag (local.get $by))))
    (if (i32.eq (local.get $sx) (i32.const 1)) (then (return (i32.sub (i32.const 0) (local.get $c)))))
    (local.get $c))
  (func $bMulMag (param $a (ref $limbs)) (param $b (ref $limbs)) (result (ref $limbs))
    (local $la i32) (local $lb i32) (local $n i32) (local $i i32) (local $j i32) (local $r (ref $limbs)) (local $carry i64) (local $cur i64) (local $ai i64)
    (local.set $la (array.len (local.get $a))) (local.set $lb (array.len (local.get $b)))
    (local.set $n (i32.add (local.get $la) (local.get $lb)))
    (local.set $r (array.new_default $limbs (local.get $n))) (local.set $i (i32.const 0))
    (block $od (loop $ol (br_if $od (i32.ge_u (local.get $i) (local.get $la)))
      (local.set $ai (array.get $limbs (local.get $a) (local.get $i))) (local.set $carry (i64.const 0)) (local.set $j (i32.const 0))
      (block $id (loop $il (br_if $id (i32.ge_u (local.get $j) (local.get $lb)))
        (local.set $cur (i64.add (i64.add (array.get $limbs (local.get $r) (i32.add (local.get $i) (local.get $j))) (i64.mul (local.get $ai) (array.get $limbs (local.get $b) (local.get $j)))) (local.get $carry)))
        (array.set $limbs (local.get $r) (i32.add (local.get $i) (local.get $j)) (i64.rem_u (local.get $cur) (i64.const 1000000000)))
        (local.set $carry (i64.div_u (local.get $cur) (i64.const 1000000000)))
        (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $il)))
      (array.set $limbs (local.get $r) (i32.add (local.get $i) (local.get $lb)) (i64.add (array.get $limbs (local.get $r) (i32.add (local.get $i) (local.get $lb))) (local.get $carry)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $ol)))
    (call $bTrim (local.get $r)))
  (func $bIsZeroVal (param $v (ref null $val)) (result i32)
    (if (result i32) (call $bIsIval (local.get $v))
      (then (i64.eqz (call $bIvalN (local.get $v))))
      (else (i32.and (i32.eq (array.len (struct.get $bigval $mag (ref.cast (ref $bigval) (local.get $v)))) (i32.const 1)) (i64.eqz (array.get $limbs (struct.get $bigval $mag (ref.cast (ref $bigval) (local.get $v))) (i32.const 0)))))))
  (func $mulVal (param $x (ref null $val)) (param $y (ref null $val)) (result (ref null $val))
    (local $a i64) (local $b i64) (local $p i64) (local $bx (ref $bigval)) (local $by (ref $bigval)) (local $sx i32) (local $sy i32)
    (if (i32.or (call $bIsZeroVal (local.get $x)) (call $bIsZeroVal (local.get $y))) (then (return (struct.new $ival (i64.const 0)))))
    (if (i32.and (call $bIsIval (local.get $x)) (call $bIsIval (local.get $y)))
      (then
        (local.set $a (call $bIvalN (local.get $x))) (local.set $b (call $bIvalN (local.get $y)))
        (local.set $p (i64.mul (local.get $a) (local.get $b)))
        (if (i32.and (i64.eq (i64.div_s (local.get $p) (local.get $a)) (local.get $b)) (i32.eqz (i32.and (i64.eq (local.get $a) (i64.const -1)) (i64.eq (local.get $b) (i64.const -9223372036854775808)))))
          (then (return (struct.new $ival (local.get $p)))))))
    (local.set $bx (call $bToBig (local.get $x))) (local.set $by (call $bToBig (local.get $y)))
    (local.set $sx (struct.get $bigval $sign (local.get $bx))) (local.set $sy (struct.get $bigval $sign (local.get $by)))
    (struct.new $bigval (i32.xor (local.get $sx) (local.get $sy)) (call $bMulMag (struct.get $bigval $mag (local.get $bx)) (struct.get $bigval $mag (local.get $by)))))
    (func $emitByte (param $b i32)
    (i32.store8 (global.get $cur) (local.get $b))
    (global.set $cur (i32.add (global.get $cur) (i32.const 1))))
  (func $emitCp (param $cp i32)
    (if (i32.lt_u (local.get $cp) (i32.const 0x80))
      (then (call $emitByte (local.get $cp)))
      (else (if (i32.lt_u (local.get $cp) (i32.const 0x800))
        (then
          (call $emitByte (i32.or (i32.const 0xC0) (i32.shr_u (local.get $cp) (i32.const 6))))
          (call $emitByte (i32.or (i32.const 0x80) (i32.and (local.get $cp) (i32.const 0x3F)))))
        (else (if (i32.lt_u (local.get $cp) (i32.const 0x10000))
          (then
            (call $emitByte (i32.or (i32.const 0xE0) (i32.shr_u (local.get $cp) (i32.const 12))))
            (call $emitByte (i32.or (i32.const 0x80) (i32.and (i32.shr_u (local.get $cp) (i32.const 6)) (i32.const 0x3F))))
            (call $emitByte (i32.or (i32.const 0x80) (i32.and (local.get $cp) (i32.const 0x3F)))))
          (else
            (call $emitByte (i32.or (i32.const 0xF0) (i32.shr_u (local.get $cp) (i32.const 18))))
            (call $emitByte (i32.or (i32.const 0x80) (i32.and (i32.shr_u (local.get $cp) (i32.const 12)) (i32.const 0x3F))))
            (call $emitByte (i32.or (i32.const 0x80) (i32.and (i32.shr_u (local.get $cp) (i32.const 6)) (i32.const 0x3F))))
            (call $emitByte (i32.or (i32.const 0x80) (i32.and (local.get $cp) (i32.const 0x3F)))))))))))
  (func $emitInt (param $n i64) (local $u i64) (local $start i32) (local $end i32) (local $t i32)
    (if (i64.lt_s (local.get $n) (i64.const 0))
      (then (call $emitByte (i32.const 45)) (local.set $u (i64.sub (i64.const 0) (local.get $n))))
      (else (local.set $u (local.get $n))))
    (local.set $start (global.get $cur))
    (block $done (loop $l
      (call $emitByte (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_u (local.get $u) (i64.const 10)))))
      (local.set $u (i64.div_u (local.get $u) (i64.const 10)))
      (br_if $l (i64.ne (local.get $u) (i64.const 0)))))
    (local.set $end (i32.sub (global.get $cur) (i32.const 1)))
    (block $rd (loop $rl
      (br_if $rd (i32.ge_s (local.get $start) (local.get $end)))
      (local.set $t (i32.load8_u (local.get $start)))
      (i32.store8 (local.get $start) (i32.load8_u (local.get $end)))
      (i32.store8 (local.get $end) (local.get $t))
      (local.set $start (i32.add (local.get $start) (i32.const 1)))
      (local.set $end (i32.sub (local.get $end) (i32.const 1)))
      (br $rl))))
  (func $put9 (param $v i64) (local $i i32) (local $start i32)
    (local.set $start (global.get $cur))
    (global.set $cur (i32.add (global.get $cur) (i32.const 9)))
    (local.set $i (i32.const 8))
    (block $done (loop $l
      (i32.store8 (i32.add (local.get $start) (local.get $i))
        (i32.add (i32.const 48) (i32.wrap_i64 (i64.rem_u (local.get $v) (i64.const 10)))))
      (local.set $v (i64.div_u (local.get $v) (i64.const 10)))
      (br_if $done (i32.eqz (local.get $i)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br $l))))
  (func $putBare (param $v i64) (local $n i32) (local $t i64) (local $i i32) (local $start i32)
    (local.set $n (i32.const 1)) (local.set $t (i64.div_u (local.get $v) (i64.const 10)))
    (block $cd (loop $cl (br_if $cd (i64.eqz (local.get $t)))
      (local.set $n (i32.add (local.get $n) (i32.const 1)))
      (local.set $t (i64.div_u (local.get $t) (i64.const 10))) (br $cl)))
    (local.set $start (global.get $cur))
    (global.set $cur (i32.add (global.get $cur) (local.get $n)))
    (local.set $i (i32.sub (local.get $n) (i32.const 1)))
    (block $done (loop $l
      (i32.store8 (i32.add (local.get $start) (local.get $i))
        (i32.add (i32.const 48) (i32.wrap_i64 (i64.rem_u (local.get $v) (i64.const 10)))))
      (local.set $v (i64.div_u (local.get $v) (i64.const 10)))
      (br_if $done (i32.eqz (local.get $i)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br $l))))
  (func $emitBig (param $b (ref $bigval)) (local $m (ref $limbs)) (local $i i32)
    (if (i32.eq (struct.get $bigval $sign (local.get $b)) (i32.const 1))
      (then (call $emitByte (i32.const 45))))
    (local.set $m (struct.get $bigval $mag (local.get $b)))
    (local.set $i (i32.sub (array.len (local.get $m)) (i32.const 1)))
    (call $putBare (array.get $limbs (local.get $m) (local.get $i)))
    (local.set $i (i32.sub (local.get $i) (i32.const 1)))
    (block $d (loop $l
      (br_if $d (i32.lt_s (local.get $i) (i32.const 0)))
      (call $put9 (array.get $limbs (local.get $m) (local.get $i)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br $l))))
  (func $isBig (param $v (ref null $val)) (result i32) (ref.test (ref $bigval) (local.get $v)))
  (func $emitLit (param $off i32) (param $len i32) (local $i i32)
    (local.set $i (i32.const 0))
    (block $d (loop $l
      (br_if $d (i32.ge_u (local.get $i) (local.get $len)))
      (call $emitByte (i32.load8_u (i32.add (local.get $off) (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $l))))
  (func $isSum (param $v (ref null $val)) (result i32) (ref.test (ref $sum) (local.get $v)))
  (func $isPair (param $v (ref null $val)) (result i32) (ref.test (ref $pair) (local.get $v)))
  (func $isIval (param $v (ref null $val)) (result i32) (ref.test (ref $ival) (local.get $v)))
  (func $isStr (param $v (ref null $val)) (result i32)
    (local $node (ref null $val)) (local $pr (ref null $val))
    (local.set $node (local.get $v))
    (if (i32.eqz (call $isSum (local.get $node))) (then (return (i32.const 0))))
    (if (i32.ne (struct.get $sum $tag (ref.cast (ref $sum) (local.get $node))) (i32.const 1))
      (then (return (i32.const 0))))
    (block $done (loop $l
      (local.set $pr (struct.get $sum $payload (ref.cast (ref $sum) (local.get $node))))
      (if (i32.eqz (call $isPair (local.get $pr))) (then (return (i32.const 0))))
      (if (i32.eqz (call $isIval (struct.get $pair 0 (ref.cast (ref $pair) (local.get $pr)))))
        (then (return (i32.const 0))))
      (local.set $node (struct.get $pair 1 (ref.cast (ref $pair) (local.get $pr))))
      (if (i32.eqz (call $isSum (local.get $node))) (then (return (i32.const 0))))
      (if (i32.eq (struct.get $sum $tag (ref.cast (ref $sum) (local.get $node))) (i32.const 0))
        (then (return (i32.const 1))))
      (br $l)))
    (i32.const 1))
  (func $emitStr (param $v (ref null $val)) (local $node (ref null $val)) (local $pr (ref null $val))
    (local.set $node (local.get $v))
    (block $done (loop $l
      (if (i32.eqz (call $isSum (local.get $node))) (then (br $done)))
      (if (i32.eq (struct.get $sum $tag (ref.cast (ref $sum) (local.get $node))) (i32.const 0))
        (then (br $done)))
      (local.set $pr (struct.get $sum $payload (ref.cast (ref $sum) (local.get $node))))
      (call $emitCp (i32.wrap_i64 (struct.get $ival 0
        (ref.cast (ref $ival) (struct.get $pair 0 (ref.cast (ref $pair) (local.get $pr)))))))
      (local.set $node (struct.get $pair 1 (ref.cast (ref $pair) (local.get $pr))))
      (br $l))))
  (func $render (param $v (ref null $val))
    (if (ref.is_null (local.get $v)) (then (call $emitLit (i32.const 0) (i32.const 2)) (return)))
    (if (call $isBig (local.get $v))
      (then (call $emitBig (ref.cast (ref $bigval) (local.get $v))) (return)))
    (if (call $isIval (local.get $v))
      (then (call $emitInt (struct.get $ival 0 (ref.cast (ref $ival) (local.get $v)))) (return)))
    (if (call $isPair (local.get $v))
      (then
        (call $emitByte (i32.const 40))
        (call $render (struct.get $pair 0 (ref.cast (ref $pair) (local.get $v))))
        (call $emitByte (i32.const 44)) (call $emitByte (i32.const 32))
        (call $render (struct.get $pair 1 (ref.cast (ref $pair) (local.get $v))))
        (call $emitByte (i32.const 41))
        (return)))
    (if (call $isSum (local.get $v))
      (then
        (if (call $isStr (local.get $v)) (then (call $emitStr (local.get $v)) (return)))
        (if (i32.eq (struct.get $sum $tag (ref.cast (ref $sum) (local.get $v))) (i32.const 0))
          (then (call $emitLit (i32.const 2) (i32.const 4)))
          (else (call $emitLit (i32.const 6) (i32.const 4))))
        (call $render (struct.get $sum $payload (ref.cast (ref $sum) (local.get $v))))
        (return)))
    (call $emitLit (i32.const 10) (i32.const 7)))
  (func $flush
    (i32.store (i32.const 4) (i32.const 16))
    (i32.store (i32.const 8) (i32.sub (global.get $cur) (i32.const 16)))
    (drop (call $fd_write (i32.const 1) (i32.const 4) (i32.const 1) (i32.const 12))))
  (elem declare func $fn0)
  (func $fn0 (type $fn) (param (ref null $env)) (param (ref null $val)) (result (ref null $val))
    (struct.get $ref 0 (ref.cast (ref $ref) (call $lookup (local.get 0) (i32.const 0)))))
  (func $_start (export "_start") (local (ref null $env)) (local (ref null $env)) (local (ref null $env)) (local (ref null $val))
    (local.set 0 (ref.null $env))
    (call $render
    (block (result (ref null $val))
    (local.set 2 (struct.new $env (block (result (ref null $val))
    (local.set 1 (struct.new $env (struct.new $ref (struct.new $ival (i64.const 0))) (local.get 0)))
    (struct.new $clos (ref.func $fn0) (local.get 1))) (local.get 0)))
    (block (result (ref null $val))
    (local.set 3 (call $lookup (local.get 2) (i32.const 0)))
    (call_ref $fn (struct.get $clos $env (ref.cast (ref $clos) (local.get 3))) (struct.new $ival (i64.const 0)) (struct.get $clos $code (ref.cast (ref $clos) (local.get 3)))))))
    (call $emitByte (i32.const 10))
    (call $flush))
)