;; put-mutation-through-shared-box: capture f={fun _ => get}, put 20, then $f() ⇒ 20 (not 7).
;; Proves the $ref box is the RIGHT rep: one-shot in-place put mutates the cell the closure holds.
(module
  (rec
    (type $val  (sub (struct)))
    (type $ival (sub $val (struct (field i64))))
    (type $ref  (sub $val (struct (field (mut (ref null $val))))))
    (type $env  (struct (field $hd (ref null $val)) (field $tl (ref null $env))))
    (type $fn   (func (param (ref null $env)) (param (ref null $val)) (result (ref null $val))))
    (type $clos (sub $val (struct (field $code (ref $fn)) (field $env (ref null $env))))))
  (func $lookup (param $e (ref null $env)) (param $n i32) (result (ref null $val))
    (block $done (loop $l (br_if $done (i32.eqz (local.get $n)))
      (local.set $e (struct.get $env $tl (local.get $e)))
      (local.set $n (i32.sub (local.get $n) (i32.const 1))) (br $l)))
    (struct.get $env $hd (local.get $e)))
  (elem declare func $fn0)
  (func $fn0 (type $fn) (param $env0 (ref null $env)) (param $arg (ref null $val)) (result (ref null $val))
    (struct.get $ref 0 (ref.cast (ref $ref) (call $lookup (local.get $env0) (i32.const 0)))))
  (func $main (export "main") (result i64)
    (local $cell (ref $ref)) (local $env (ref null $env)) (local $clos (ref $clos))
    (local.set $cell (struct.new $ref (struct.new $ival (i64.const 7))))
    (local.set $env (struct.new $env (local.get $cell) (ref.null $env)))
    (local.set $clos (struct.new $clos (ref.func $fn0) (local.get $env)))
    ;; put 20 = mutate the box in place (resume in place, no unwind)
    (struct.set $ref 0 (local.get $cell) (struct.new $ival (i64.const 20)))
    (struct.get $ival 0 (ref.cast (ref $ival)
      (call_ref $fn (struct.get $clos $env (local.get $clos)) (ref.null $val)
                    (struct.get $clos $code (local.get $clos))))))
)
