#!/usr/bin/env python3
# tool: role=check couples=docs/notes/*.md,tools/doc-pins-baseline.txt runs-in=fitness
"""check-doc-pins.py — doc-staleness detection over git's Merkle DAG.

Every prose note in docs/notes/ declares its dependency posture with a
`describes:` marker near the top (line 2 by convention, after note-status):

    <!-- describes: Bang/Backend/WasmEmit.lean tools/emit-escape-diff.sh @ <sha> -->
    <!-- describes: none -->

  * paths + `@ <sha>`  — the note DESCRIBES those sources, pinned at the
    commit where the prose was last verified against them. Staleness =
    git's blob/tree hash at the pin differs from HEAD's (git supplies the
    hash, the diff, AND the why: the commits in between).
  * `none`             — EXPLICIT opt-out: the note intentionally tracks no
    source (pure survey/history). Nothing is exempt silently.

Notes that predate the convention live in tools/doc-pins-baseline.txt —
a checked-in, SHRINK-ONLY list: they are reported loudly, a new/renamed
note missing the marker FAILS, and stamping a baseline note requires
pruning it from the list (the ratchet).

The ripple: a note citing a STALE note is flagged for review (one hop —
transitive prose-of-prose review chains add noise faster than signal).

Restamping = the review ritual: re-read the note against
`git log <pin>..HEAD -- <paths>`, amend or confirm, bump the pin sha.
Repeated restamps of the same claim = the signal to promote it up the
derivation ladder (generate or #guard it) instead — detection is the
floor, not the goal (the stranger-test-5 finding).

Exit: structural violations always fail (missing marker off-baseline,
baseline growth, dangling path, bad sha). Staleness warns by default;
`--strict` (the release checklist) makes it fail too.
"""

from __future__ import annotations
import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTES = ROOT / "docs" / "notes"
BASELINE = ROOT / "tools" / "doc-pins-baseline.txt"

DESCRIBES = re.compile(r"<!--\s*describes:\s*(.+?)\s*-->")
GENERATED = re.compile(r"<!--\s*GENERATED by ")


def git(*args: str) -> tuple[int, str]:
    p = subprocess.run(["git", *args], capture_output=True, text=True, cwd=ROOT)
    return p.returncode, p.stdout.strip()


def obj_hash(rev: str, path: str) -> str | None:
    rc, out = git("rev-parse", "-q", "--verify", f"{rev}:{path}")
    return out if rc == 0 else None


def parse_marker(text: str) -> tuple[str, list[str], str | None] | None:
    """Return (kind, paths, sha): kind ∈ {'none','pinned'}; None if absent."""
    m = DESCRIBES.search(text[:2000])
    if not m:
        return None
    body = m.group(1)
    if body.strip() == "none":
        return ("none", [], None)
    if "@" in body:
        paths_part, sha = body.rsplit("@", 1)
        return ("pinned", paths_part.split(), sha.strip())
    return ("pinned", body.split(), None)  # malformed: pinned without sha


def load_baseline() -> list[str]:
    if not BASELINE.exists():
        return []
    return [
        line.strip()
        for line in BASELINE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true",
                    help="stale pins fail too (release-checklist tier)")
    args = ap.parse_args()

    fails: list[str] = []
    stale: dict[str, list[str]] = {}
    pinned_ok = optout = 0

    notes = sorted(p for p in NOTES.glob("*.md"))
    baseline = load_baseline()
    undeclared: list[str] = []
    names = {p.name for p in notes}

    for note in notes:
        text = note.read_text(encoding="utf-8")
        if GENERATED.search(text[:400]):
            continue  # top-rung: generated docs are gated by their generator's --check
        marker = parse_marker(text)
        if marker is None:
            undeclared.append(note.name)
            continue
        kind, paths, sha = marker
        if kind == "none":
            optout += 1
            continue
        if not sha or not re.fullmatch(r"[0-9a-f]{7,40}", sha):
            fails.append(f"{note.name}: describes-marker lacks a valid `@ <sha>` pin")
            continue
        if not paths:
            fails.append(f"{note.name}: describes-marker has a sha but no paths")
            continue
        reasons: list[str] = []
        for path in paths:
            head = obj_hash("HEAD", path)
            if head is None:
                fails.append(f"{note.name}: describes `{path}` which does not exist at HEAD (dangling edge)")
                continue
            pin = obj_hash(sha, path)
            if pin != head:
                _, why = git("log", "--oneline", f"{sha}..HEAD", "--", path)
                head_why = " · ".join(why.splitlines()[:3]) or "(pinned sha predates path)"
                reasons.append(f"{path} moved since {sha[:10]}: {head_why}")
        if reasons:
            stale[note.name] = reasons
        else:
            pinned_ok += 1

    # baseline ratchet: shrink-only
    for name in undeclared:
        if name not in baseline:
            fails.append(
                f"{name}: no `<!-- describes: … @ <sha> -->` marker and not in the "
                f"baseline — declare its sources, or `<!-- describes: none -->` to opt out"
            )
    for name in baseline:
        if name not in names:
            fails.append(f"baseline lists `{name}` which no longer exists — prune tools/doc-pins-baseline.txt")
        elif name not in undeclared:
            fails.append(f"baseline lists `{name}` which now declares — prune it from tools/doc-pins-baseline.txt (the ratchet)")

    # the ripple: one hop of citations into stale notes
    review: dict[str, list[str]] = {}
    if stale:
        stale_names = set(stale)
        for note in notes:
            if note.name in stale_names:
                continue
            body = note.read_text(encoding="utf-8")
            if GENERATED.search(body[:400]):
                continue  # generated docs regenerate; they don't need prose review
            cited = {n for n in stale_names if n != note.name and n in body}
            if cited:
                review[note.name] = sorted(cited)

    print("── doc-pins ──")
    print(f"pinned fresh: {pinned_ok}   opted out (describes: none): {optout}   "
          f"baseline (undeclared, shrink-only): {len(undeclared)}")
    for name, reasons in sorted(stale.items()):
        print(f"STALE  {name}")
        for r in reasons:
            print(f"       {r}")
        print(f"       → re-verify the prose, then restamp: describes … @ $(git rev-parse HEAD)")
    for name, cited in sorted(review.items()):
        print(f"REVIEW {name} cites stale: {', '.join(cited)}")
    for f in fails:
        print(f"FAIL   {f}")

    if fails:
        return 1
    if stale and args.strict:
        print("FAIL: stale pins under --strict (release tier)")
        return 1
    if stale:
        print(f"warn: {len(stale)} stale note(s) — not a fitness failure; "
              f"`--strict` gates them at release")
    else:
        print("PASS: every declared pin is fresh.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
