#!/usr/bin/env python3
# tool: role=gen couples=Bang/Audit.lean,docfacts/proof-claims.json,audit_facts.py,burndown.sh,CONTEXT.md,genblock.py runs-in=fitness
"""gen-proof-state.py — generate CONTEXT.md's proof-state line from the gate (the root).

CONTEXT.md hand-maintains a "proof-state" summary (which headline theorems are
axiom-clean · the sorry count · the sha). That is a SURVEY of `Bang/Audit.lean`
(the 24 `#print axioms <thm>` headlines) + `tools/burndown.sh` + `git` — copies of
facts that drift. This regenerates that summary from those roots, the same move as
`gen-adr-index.py` / `gen-gate-index.py` (the generate>test>convention ladder).

TREE-AWARENESS (why this is a fresh tool, not a copy of the others):
  Proof-state lives in `Audit.lean`, which is only current on the PROOF worktrees;
  the DOCS tree (where CONTEXT.md lives) carries stale / in-flight Lean. So the
  root we read (`--lean-root`) is decoupled from the doc we write (`--context`).
  And the gate is olean-backed: a warm olean can report a stale axiom set, so a
  real claim is read only after a force-rebuild (`touch` always; `--build` runs
  `lake build Bang.Audit` for an authoritative render).

  `--check` DEGRADES GRACEFULLY: if `lake` is unavailable, or no headline's
  `#print axioms` actually printed (Audit not buildable — the normal docs-tree
  state AND mid-reshape on the proof trees), it SKIPs (exit 0) rather than fail.
  Only when Audit builds and headlines print does it assert the committed block
  ≡ a fresh render. This is what lets it ride `just fitness` now (no build gate)
  and auto-activate when a proof tree goes green.

Zero dependencies (stdlib), like the other tools/ scripts.

Usage:
    gen-proof-state.py                       # rewrite the block in ./CONTEXT.md
    gen-proof-state.py --lean-root ../proof  # read Audit/burndown/git from there
    gen-proof-state.py --build               # force `lake build Bang.Audit` first
    gen-proof-state.py --check               # SKIP if not buildable; else gate drift
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter

from audit_facts import axiom_report, classify, headlines, parse_axioms, run
from genblock import splice as _splice
from provenance import ProvenanceError, bang_tree, proof_input_id

BEGIN = "<!-- BEGIN GENERATED proof-state (just proof-state) — do not hand-edit -->"
END = "<!-- END GENERATED proof-state -->"
TOTAL_RE = re.compile(r"^TOTAL\s+(\d+)\s+(\d+)\s+(\d+)")


def sorry_total(lean_root: str):
    """The burndown sorry count (TOTAL row, sorry column), or None if it can't run."""
    res = run(["bash", "tools/burndown.sh"], lean_root)
    if res is None or res[0] != 0:
        return None
    for line in res[1].splitlines():
        m = TOTAL_RE.match(line)
        if m:
            return int(m.group(1))
    return None


def semantic_inventory(lean_root: str) -> dict[str, dict]:
    path = os.path.join(lean_root, "docfacts", "proof-claims.json")
    with open(path, encoding="utf-8") as stream:
        claims = json.load(stream)["claims"]
    refs = [item["writtenRef"] for item in claims]
    enrolled = headlines(lean_root)
    if len(refs) != len(set(refs)) or set(refs) != set(enrolled):
        raise ValueError(
            "proof-claim semantics must cover Audit enrollments exactly by writtenRef"
        )
    return {item["writtenRef"]: item for item in claims}


def render(lean_root: str, report: dict[str, list[str]], end: str = "HEAD") -> str:
    clean, pending, flagged = classify(lean_root, report)
    semantics = semantic_inventory(lean_root)
    substantive_roles = {"canonical", "supporting"}
    aliases = [
        ref
        for ref, item in semantics.items()
        if item["claimRole"] in {"alias", "deprecated-alias"}
    ]
    placeholders = [
        ref for ref, item in semantics.items() if item["claimRole"] == "placeholder"
    ]
    clean_claims = [
        ref for ref in clean if semantics[ref]["claimRole"] in substantive_roles
    ]
    pending_claims = [
        ref for ref in pending if semantics[ref]["claimRole"] in substantive_roles
    ]
    flagged_claims = [
        (ref, axioms)
        for ref, axioms in flagged
        if semantics[ref]["claimRole"] in substantive_roles
    ]
    role_counts = Counter(item["claimRole"] for item in semantics.values())
    strength_counts = Counter(item["claimStrength"] for item in semantics.values())
    alias_count = role_counts["alias"] + role_counts["deprecated-alias"]
    s = sorry_total(lean_root)
    lines = [
        BEGIN,
        "_Generated by `tools/gen-proof-state.py --lean-root <…>`. "
        f"Proof-state for Bang tree `tree:{bang_tree(lean_root, end)}`; "
        f"inputs `proof-input:{proof_input_id(lean_root, end)}`._",
        "",
        f"- **claims:** {len(clean_claims)} trusted-axiom (⊆ trusted-3) · "
        f"{len(pending_claims)} pending (build in flight) · {len(flagged_claims)} flagged "
        "(aliases/placeholders excluded)",
        f"- **semantic strength:** {strength_counts['strong']} strong · "
        f"{strength_counts['structural']} structural · {strength_counts['bounded']} bounded · "
        f"{strength_counts['partial']} partial · {strength_counts['conjectural']} conjectural",
        f"- **enrollment roles:** {role_counts['canonical']} canonical · "
        f"{role_counts['supporting']} supporting · {alias_count} aliases · "
        f"{role_counts['placeholder']} placeholder",
    ]
    for name, axs in flagged_claims:
        lines.append(f"- **flagged:** `{name}` → [{', '.join(axs)}]")
    for name in placeholders:
        axioms = next((axs for ref, axs in flagged if ref == name), [])
        lines.append(f"- **placeholder:** `{name}` → [{', '.join(axioms)}]")
    lines.append(f"- **aliases:** {', '.join(f'`{name}`' for name in aliases)}")
    lines.append(
        f"- **sorries:** {s if s is not None else 'unknown'} (per `burndown.sh`)"
    )
    lines.append(END)
    return "\n".join(lines)


def splice(md: str, block: str) -> str:
    return _splice(md, BEGIN, END, block)


def buildable(report, lean_root) -> bool:
    """Audit is buildable iff at least one headline's axiom report actually printed."""
    _, pending, _ = classify(lean_root, report)
    return len(pending) < len(headlines(lean_root))


def main() -> int:
    try:
        __import__("subprocess").run(
            [
                "bash",
                __import__("os").path.join(
                    __import__("os").path.dirname(__file__), "tool-log.sh"
                ),
                __import__("os").path.basename(__file__),
            ],
            check=False,
        )  # tool-log (plan 012)
    except Exception:
        pass
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--lean-root", default=".", help="where to run lake/git (default: cwd)"
    )
    ap.add_argument(
        "--context", default=None, help="doc to write (default: <lean-root>/CONTEXT.md)"
    )
    ap.add_argument(
        "--build", action="store_true", help="force `lake build Bang.Audit` first"
    )
    ap.add_argument(
        "--check", action="store_true", help="SKIP if not buildable; else gate drift"
    )
    ap.add_argument(
        "--end",
        default=os.environ.get("PROVENANCE_END", "HEAD"),
        help="history endpoint whose Bang tree is claimed",
    )
    args = ap.parse_args()

    lean_root = os.path.abspath(args.lean_root)
    context = os.path.abspath(args.context or os.path.join(lean_root, "CONTEXT.md"))

    report_text = axiom_report(lean_root, build=args.build)
    report = parse_axioms(report_text) if report_text is not None else {}

    if args.check:
        # Degrade gracefully: lake missing, or Audit not buildable → SKIP (don't fail).
        if report_text is None:
            print(
                "── proof-state ──\nSKIP: `lake` unavailable in "
                f"{lean_root} (proof-state check inactive)."
            )
            return 0
        if not buildable(report, lean_root):
            print(
                "── proof-state ──\nSKIP: Audit.lean not buildable in "
                f"{lean_root} (proof-state check inactive until the tree greens)."
            )
            return 0
        block = render(lean_root, report, args.end)
        md = open(context, encoding="utf-8").read()
        if BEGIN not in md or END not in md:
            print(
                f"── proof-state ──\nFAIL: {context} has no GEN markers — run `just proof-state`."
            )
            return 1

        if splice(md, block) != md:
            print(
                "── proof-state ──\nFAIL: CONTEXT.md proof-state block is stale "
                "— run `just proof-state`."
            )
            return 1
        print("── proof-state ──\nPASS: proof-state content ≡ the live axiom gate.")
        return 0

    try:
        block = render(lean_root, report, args.end)
    except ProvenanceError as exc:
        print(f"proof-state: cannot derive Bang tree: {exc}", file=sys.stderr)
        return 1
    md = open(context, encoding="utf-8").read()
    if BEGIN not in md or END not in md:
        print(
            f"proof-state: {context} has no GEN markers — add them to enable generation.",
            file=sys.stderr,
        )
        return 1
    open(context, "w", encoding="utf-8").write(splice(md, block))
    print(
        f"proof-state: regenerated the block in {os.path.relpath(context, lean_root)}."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
