#!/usr/bin/env python3
"""gen-import-graph.py — the module dependency graph, generated from the `import` edges.

`docs/architecture/core-overview.md` §2 carried a HAND-DRAWN module graph that drifted
(it listed Metatheory 3501 / Core 320 / Operational 949; actual 2560 / 344 / 870). This
derives the graph + per-module LOC + fan-in from the actual `import Bang.*` lines, grouped
by architectural TIER — so the picture cannot drift, and the tiering doubles as the
restructure target (task #17). Same move as gen-adr-index / gen-gate-index; `--check` fails
on drift. `just import-graph` prints the mermaid to stdout.

Tiers are the TARGET structure (the post-reshape directory layout); the files are still flat
in Bang/ today (the move is gated on a green tree). The map here is the single source for
both the diagram and, later, `arch-check`'s path-derived layer.
"""
import os
import re
import sys

ROOT = os.path.abspath(os.environ.get("REFS_ROOT", "."))
BANG = os.path.join(ROOT, "Bang")
DOC = os.path.join(ROOT, "docs/architecture/core-overview.md")
GEN_BEGIN = "<!-- BEGIN GENERATED import-graph (just import-graph) — do not hand-edit -->"
GEN_END = "<!-- END GENERATED import-graph -->"

# module → target tier. Order = top-to-bottom in the diagram. (Files are flat today; this is
# the restructure target, and the single source for arch-check's future path-derived layer.)
TIER = {
    "EffectRow": "Core", "Mult": "Core", "Core": "Core", "Syntax": "Core", "Operational": "Core",
    "Surface": "Frontend", "Surface.Trait": "Frontend", "Frontend.NamedCore": "Frontend",
    "CalcVM": "Backend", "Compile": "Backend",
    "Metatheory": "Meta", "LR": "Meta", "Compat": "Meta",
    "Spec": "Apex", "Audit": "Apex", "Distribution": "Apex",
    "CapEscapeWitness": "Regress", "LWRegress": "Regress",
    "CalcReify": "Reify", "CalcReifyRef": "Reify", "CalcReifySim": "Reify",
}
TIER_ORDER = ["Frontend", "Core", "Backend", "Meta", "Apex", "Regress", "Reify"]
TIER_LABEL = {
    "Core": "Core — IR · typing · KERNEL (the narrow waist)",
    "Frontend": "Frontend — text → IR",
    "Backend": "Backend — calc-VM → WasmFX",
    "Meta": "Meta — soundness + logical relations (the proofs)",
    "Apex": "Apex — verification spine + gate",
    "Regress": "Regress — build-gated witnesses",
    "Reify": "Reify — ADR-0015 paused reification frontier (standalone island)",
}


def scan():
    """module -> (loc, [imported modules]). Module name uses dots for subdirs (Frontend.NamedCore)."""
    mods = {}
    for dp, _, files in os.walk(BANG):
        for f in files:
            if not f.endswith(".lean"):
                continue
            path = os.path.join(dp, f)
            rel = os.path.relpath(path, BANG)[:-5].replace(os.sep, ".")
            text = open(path, encoding="utf-8").read()
            loc = text.count("\n") + 1
            imps = re.findall(r"^import Bang\.([A-Za-z][\w.]*)", text, re.MULTILINE)
            mods[rel] = (loc, imps)
    return mods


def render(mods):
    fanin = {m: 0 for m in mods}
    for _, (_, imps) in mods.items():
        for i in imps:
            if i in fanin:
                fanin[i] += 1

    def node_id(m):
        return m.replace(".", "_")

    lines = [GEN_BEGIN,
             "_Generated by `tools/gen-import-graph.py` from the `import Bang.*` edges. "
             "Node label = `module (LOC · fan-in)`. Tiers are the restructure target (task #17); "
             "files are flat in `Bang/` until the post-reshape move._", "", "```mermaid", "graph TD"]
    # subgraph per tier (only tiers that have modules)
    by_tier = {t: [] for t in TIER_ORDER}
    for m in mods:
        by_tier.setdefault(TIER.get(m, "Core"), []).append(m)
    for t in TIER_ORDER:
        members = sorted(by_tier.get(t, []))
        if not members:
            continue
        # subgraph id is prefixed (`tier_…`) so it never collides with a node id
        # (e.g. the `Core` module node vs a `Core` tier); `<br/>` is mermaid's line
        # break — a literal newline in a node label breaks the parse.
        lines.append(f'  subgraph tier_{t}["{TIER_LABEL[t]}"]')
        for m in members:
            loc, _ = mods[m]
            lines.append(f'    {node_id(m)}["{m}<br/>{loc}L · fan-in {fanin[m]}"]')
        lines.append("  end")
    # edges: importer --> imported (A → B means A imports B)
    for m, (_, imps) in sorted(mods.items()):
        for i in imps:
            if i in mods:
                lines.append(f"  {node_id(m)} --> {node_id(i)}")
    lines.append("```")
    # compact fan-in table (the waist-vs-leaf read)
    lines += ["", "| module | tier | LOC | fan-in |", "|---|---|---|---|"]
    for m in sorted(mods, key=lambda m: (-fanin[m], m)):
        lines.append(f"| `{m}` | {TIER.get(m, '?')} | {mods[m][0]} | {fanin[m]} |")
    lines.append(GEN_END)
    return "\n".join(lines)


def splice(md, block):
    return re.sub(re.escape(GEN_BEGIN) + r".*?" + re.escape(GEN_END), block, md, flags=re.DOTALL)


def validate_mermaid(block):
    """Render the mermaid fence with `mmdc` — returns ('pass'|'fail'|'skip', msg).
    `--check` only confirms the TEXT matches the import edges; THIS confirms the diagram
    actually COMPILES (catches generator bugs like a raw newline in a label or a
    subgraph-id ⟂ node-id clash — exactly the bug this check was added for)."""
    import shutil
    import subprocess
    import tempfile
    if not shutil.which("mmdc"):
        return ("skip", "mmdc not on PATH (it's in the dev shell — `nix develop`); compile-check skipped")
    m = re.search(r"```mermaid\n(.*?)\n```", block, re.DOTALL)
    if not m:
        return ("skip", "no mermaid fence in the generated block")
    d = tempfile.mkdtemp()
    mmd, cfg, svg = (os.path.join(d, x) for x in ("g.mmd", "pptr.json", "g.svg"))
    open(mmd, "w").write(m.group(1))
    open(cfg, "w").write('{"args":["--no-sandbox","--disable-gpu"]}')  # sandboxed env needs --no-sandbox
    try:
        r = subprocess.run(["mmdc", "-i", mmd, "-o", svg, "-p", cfg],
                           capture_output=True, text=True, timeout=180)
        ok = r.returncode == 0 and os.path.exists(svg)
        return ("pass", "mermaid compiles (mmdc render OK)") if ok else \
               ("fail", (r.stderr or r.stdout).strip()[-500:])
    finally:
        shutil.rmtree(d, ignore_errors=True)


def main():
    args = sys.argv[1:]
    mods = scan()
    block = render(mods)
    if not os.path.exists(DOC):
        print(f"import-graph: {DOC} missing", file=sys.stderr)
        return 1
    md = open(DOC, encoding="utf-8").read()
    if GEN_BEGIN not in md or GEN_END not in md:
        print(f"import-graph: {DOC} has no GEN markers — add them under §2 to enable.", file=sys.stderr)
        return 1

    if "--validate" in args:  # compile the COMMITTED diagram
        cm = re.search(re.escape(GEN_BEGIN) + r"(.*?)" + re.escape(GEN_END), md, re.DOTALL)
        status, msg = validate_mermaid(cm.group(1) if cm else "")
        print(f"── import-graph (mermaid compile) ──\n{status.upper()}: {msg}")
        return 1 if status == "fail" else 0

    new = splice(md, block)
    if "--check" in args:  # drift only (fast, no mmdc — runs every commit)
        if new != md:
            print("── import-graph ──\nFAIL: core-overview.md §2 graph is stale — run `just import-graph`.")
            return 1
        print("── import-graph ──\nPASS: module graph ≡ the import edges.")
        return 0

    # build: COMPILE the fresh diagram before persisting — never write a broken graph
    status, msg = validate_mermaid(block)
    if status == "fail":
        print(f"── import-graph ──\nFAIL: generated mermaid does not compile (NOT written):\n{msg}")
        return 1
    open(DOC, "w", encoding="utf-8").write(new)
    tail = "mermaid compiles ✓" if status == "pass" else f"(compile-check {status}: {msg})"
    print(f"import-graph: regenerated §2 graph ({len(mods)} modules). {tail}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
