#!/usr/bin/env python3
"""Generate docs/reference/language.md — a DERIVATION of the code, never hand-maintained.

Sources of truth (the generate rung of the derivation ladder):
  • Bang/Frontend/Surface.lean — the `Surf` and `Ty` inductives. Each constructor's trailing
    `-- comment` IS the surface form, so they generate the SYNTAX + TYPES reference.
  • Bang/Examples.lean + Bang/Frontend/TypeCheck.lean — the `#guard` corpus. `runYieldsInt "src" N`
    (program ⟹ value) and `display "src" == "type"` (program : type) generate the EXAMPLES reference.
    Every example is gated by `lake build`, so a doc derived from them CANNOT drift.

Usage:  gen-reference.py            regenerate docs/reference/language.md
        gen-reference.py --check    exit 1 if the committed doc != the regenerated one (fitness leg)
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SURFACE = ROOT / "Bang/Frontend/Surface.lean"
IR = ROOT / "Bang/Core/IR.lean"
SOURCES = [ROOT / "Bang/Examples.lean", ROOT / "Bang/Frontend/TypeCheck.lean"]
OUT = ROOT / "docs/reference/language.md"

STR = r'"((?:[^"\\]|\\.)*)"'  # a Lean string literal (with escapes)


def first_sentence(s):
    s = re.sub(r"\s+", " ", s).strip()
    m = re.match(r"(.*?\.)(?:\s|$)", s)
    return (m.group(1) if m else s).strip()


def extract_labels(text):
    """(name, value, summary) for each `/-- … -/ def <name>Label : Label := <n>`."""
    rows = []
    for m in re.finditer(r"/--(.*?)-/\s*def\s+(\w+Label)\s*:\s*Label\s*:=\s*(\d+)", text, re.S):
        rows.append((m.group(2), m.group(3), first_sentence(m.group(1))))
    return rows


def extract_constructors(text, name):
    """(ctor, signature, comment) for `inductive <name>` (line-based; stops at the inductive's end)."""
    rows, capturing = [], False
    for line in text.splitlines():
        s = line.strip()
        if re.match(rf"inductive {name}\b", s):
            capturing = True
            continue
        if not capturing:
            continue
        if s.startswith("|"):
            cm = re.match(r"\|\s*(\w+)\s*:\s*([^-]*?)\s*(?:--\s*(.*))?$", s)
            if cm:
                rows.append((cm.group(1), cm.group(2).strip(), (cm.group(3) or "").strip()))
        elif s.startswith(("deriving", "inductive", "end", "def", "@", "abbrev")):
            break
    return rows


def extract_inductive(text, name):
    """`| ctor : sig  -- comment` rows of `inductive <name> where … deriving`."""
    m = re.search(rf"inductive {name} where\n(.*?)\n\s*deriving", text, re.S)
    if not m:
        return []
    rows = []
    for line in m.group(1).splitlines():
        cm = re.match(r"\s*\|\s*(\w+)\s*:.*?--\s*(.*)", line)
        if cm:
            # the comment is `<form>   <note>` (2+ spaces separate the form from any description)
            parts = re.split(r"\s{2,}", cm.group(2).strip(), maxsplit=1)
            form = parts[0]
            note = parts[1].strip() if len(parts) > 1 else ""
            rows.append((cm.group(1), form, note))
    return rows


def parse_examples(path):
    """(section, comment, kind, src, result) for each runYieldsInt / display #guard."""
    lines = path.read_text().splitlines()
    section, comment, out, i = None, None, [], 0
    while i < len(lines):
        s = lines[i].strip()
        hm = re.match(r"/-!\s*#+\s*(.*)", s)
        if hm:
            section = re.sub(r"\s*-/\s*$", "", hm.group(1)).strip()
            comment = None
            i += 1
            continue
        if s.startswith("--"):
            comment = s.lstrip("-").strip()
            i += 1
            continue
        if s.startswith("#guard"):
            stmt, j = s, i + 1
            while j < len(lines):  # join continuation lines (multi-line #guards)
                nxt = lines[j].strip()
                if nxt == "" or nxt.startswith(("#guard", "/-!", "--")):
                    break
                stmt += " " + nxt
                j += 1
            mv = re.search(rf"runYieldsInt\s+\d+\s+{STR}\s+(-?\d+)", stmt)
            if mv:
                out.append((section, comment, "value", mv.group(1), mv.group(2)))
            mt = re.search(rf"display\s+{STR}\s*==\s*{STR}", stmt)
            if mt:
                out.append((section, comment, "type", mt.group(1), mt.group(2)))
            comment = None
            i = j
            continue
        if s == "":
            comment = None
        i += 1
    return out


def render():
    surf = SURFACE.read_text()
    L = []
    L.append("# BANG — language reference")
    L.append("")
    L.append("<!-- GENERATED by tools/gen-reference.py from the verified source — do not hand-edit. -->")
    L.append("<!-- Run `just reference` to regenerate; `gen-reference.py --check` gates it. -->")
    L.append("")
    L.append("Derived from the code: the surface forms are the `Surf`/`Ty` constructor comments in")
    L.append("`Bang/Frontend/Surface.lean`; every example is a `#guard` gated by `lake build`, so")
    L.append("nothing here can drift from what the language actually does.")
    L.append("")

    L.append("## Surface syntax")
    L.append("")
    L.append("| Form | Notes |")
    L.append("|---|---|")
    for _name, form, note in extract_inductive(surf, "Surf"):
        L.append(f"| `{form}` | {note} |")
    L.append("")

    L.append("## Types")
    L.append("")
    L.append("| Type | Notes |")
    L.append("|---|---|")
    for _name, form, note in extract_inductive(surf, "Ty"):
        L.append(f"| `{form}` | {note} |")
    L.append("")

    L.append("## Effect channels")
    L.append("")
    L.append("The surface's effect labels (the frozen v1 set). A handler on a label discharges its row;")
    L.append("an undischarged label surfaces in the inferred effect (see Examples → type display).")
    L.append("")
    L.append("| Label | Value | Channel |")
    L.append("|---|---|---|")
    for name, val, summ in extract_labels(surf):
        L.append(f"| `{name}` | {val} | {summ} |")
    L.append("")

    L.append("## Kernel primitives (the IR the surface lowers to)")
    L.append("")
    L.append("The graded-CBPV kernel — `Val` (values), `Comp` (computations), `Handler` (effect handlers).")
    L.append("The surface is sugar over these; `Source.eval` (Bang/Core/IR.lean) is the reference semantics.")
    L.append("")
    ir = IR.read_text()
    for ind, heading in [("Val", "Values"), ("Comp", "Computations"), ("Handler", "Handlers")]:
        L.append(f"### {heading} (`{ind}`)")
        L.append("")
        L.append("| Primitive | Signature | Notes |")
        L.append("|---|---|---|")
        for ctor, sig, note in extract_constructors(ir, ind):
            L.append(f"| `{ctor}` | `{sig}` | {note} |")
        L.append("")

    L.append("## Examples")
    L.append("")
    L.append("Every example below is a build-verified `#guard`. `⟹` is evaluation; `:` is the inferred type.")
    L.append("")
    rows = [r for p in SOURCES for r in parse_examples(p)]
    cur = None
    for section, comment, kind, src, result in rows:
        if section != cur:
            cur = section
            L.append(f"### {section}")
            L.append("")
        arrow = "⟹" if kind == "value" else ":"
        note = f"  — {comment}" if comment else ""
        L.append(f"- `{src}` {arrow} `{result}`{note}")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    content = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print("reference: STALE — docs/reference/language.md != regenerated. Run `just reference`.")
            sys.exit(1)
        print("reference: OK — language.md ≡ the verified source.")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    n = content.count("\n- `")
    print(f"reference: wrote {OUT.relative_to(ROOT)} ({n} verified examples).")


if __name__ == "__main__":
    main()
