#!/usr/bin/env python3
"""gen-questions-index.py — the design-question ledger, generated from the OKF files.

`docs/notes/questions/*.md` is a flat folder of one-question-per-file notes, each
carrying OKF-shaped frontmatter (`type`/`title`/`description` + `status`/`area`/`ties`).
This renders `docs/notes/questions/INDEX.md`: an always-current index grouped by
`area` then `status`, plus a **mermaid tie-graph** of the `ties` edges. The index is a
pure function of the files + their frontmatter — it cannot drift (the ADR-ledger /
gen-notes-index pattern applied to the question ledger).

The POINT of the structure is VALIDATED EDGES: every `ties:` entry must name a real
question (`Q<N>` in the monolith or a question file) or a real ADR (`docs/decisions/`).
A dangling tie is a `sys.exit` (`see-also` is freeform, NOT validated).

  gen-questions-index.py           # regenerate docs/notes/questions/INDEX.md
  gen-questions-index.py --check   # exit 1 if it is stale (round-trip gate, for fitness)
"""
import os
import re
import sys

from genblock import validate_mermaid  # reuse the import-graph mermaid compile-check

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
QDIR = os.path.join(ROOT, "docs", "notes", "questions")
MONO = os.path.join(ROOT, "docs", "notes", "OPEN_QUESTIONS.md")
DECISIONS = os.path.join(ROOT, "docs", "decisions")
OUT = os.path.join(QDIR, "INDEX.md")

AREA_ORDER = ["type-system", "effects", "surface", "tooling", "meta"]
STATUS_ORDER = ["open", "resolved"]
REQUIRED = ["type", "title", "description", "status", "area", "ties", "see-also"]


def parse_frontmatter(text, path):
    m = re.match(r"---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        sys.exit(f"gen-questions-index: {path} has no `---`-delimited frontmatter.")
    fm = {}
    for line in m.group(1).splitlines():
        if not line.strip():
            continue
        km = re.match(r"([\w-]+):\s*(.*)$", line)
        if not km:
            sys.exit(f"gen-questions-index: malformed frontmatter line in {path}: {line!r}")
        key, val = km.group(1), km.group(2).strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            fm[key] = [x.strip().strip('"').strip("'") for x in inner.split(",")] if inner else []
        else:
            fm[key] = val.strip('"').strip("'")
    missing = [k for k in REQUIRED if k not in fm]
    if missing:
        sys.exit(f"gen-questions-index: {path} frontmatter missing {missing}.")
    if fm["area"] not in AREA_ORDER:
        sys.exit(f"gen-questions-index: {path} has unknown area {fm['area']!r} "
                 f"(taxonomy: {AREA_ORDER}).")
    return fm


def load_questions():
    """[(qid, frontmatter)] sorted by qid, from docs/notes/questions/Q*.md."""
    out = []
    for fn in sorted(os.listdir(QDIR)):
        if not re.match(r"Q\d+-.*\.md$", fn):
            continue
        qid = re.match(r"(Q\d+)-", fn).group(1)
        fm = parse_frontmatter(open(os.path.join(QDIR, fn), encoding="utf-8").read(),
                               f"docs/notes/questions/{fn}")
        fm["_file"] = fn
        fm["_slug"] = re.match(r"Q\d+-(.*)\.md$", fn).group(1)
        out.append((qid, fm))
    out.sort(key=lambda p: int(p[0][1:]))
    return out


def valid_ids(questions):
    """The set of link targets a tie may point at: monolith Q-ids ∪ file Q-ids ∪ ADR-ids."""
    ids = set()
    mono = open(MONO, encoding="utf-8").read()
    ids |= set(re.findall(r"^## (Q\d+)\b", mono, re.MULTILINE))
    ids |= {qid for qid, _ in questions}
    for fn in os.listdir(DECISIONS):
        dm = re.match(r"(\d{4})-.*\.md$", fn)
        if dm:
            ids.add(f"ADR-{dm.group(1)}")
    return ids


def mono_titles():
    """qid -> short title, parsed from the monolith `## Q<N> — <title> …` headers."""
    out = {}
    for m in re.finditer(r"^## (Q\d+) — (.*)$", open(MONO, encoding="utf-8").read(), re.MULTILINE):
        out[m.group(1)] = m.group(2)
    return out


def short(title):
    """A compact node label: the phrase before the first `:`/`(`/`·`, trimmed."""
    head = re.split(r"[:(·]", title, maxsplit=1)[0].strip()
    return head if len(head) <= 34 else head[:31].rstrip() + "…"


def node_id(link):
    return link.replace("-", "_")


def render(questions, ids):
    titles = mono_titles()
    label_short = {qid: fm["_slug"] for qid, fm in questions}

    def target_label(link):
        if link.startswith("ADR-"):
            return link
        if link in label_short:
            return f"{link} · {label_short[link]}"
        if link in titles:
            return f"{link} · {short(titles[link])}"
        return link

    L = ["# Design-question ledger — INDEX",
         "",
         "<!-- GENERATED by tools/gen-questions-index.py — do not hand-edit. Regenerate with "
         "`just questions-index`; `--check` gates it in `just fitness`. -->",
         "",
         "> One file per question under `docs/notes/questions/` (OKF-shaped: `type`/`title`/",
         "> `description` frontmatter + `status`/`area`/`ties`). This index and the tie-graph below",
         "> are a pure function of those files — they cannot drift. `ties` edges are VALIDATED",
         "> (a tie to a nonexistent question/ADR fails the generator); `see-also` is freeform.",
         "",
         "## Index",
         ""]

    by_area = {a: [] for a in AREA_ORDER}
    for qid, fm in questions:
        by_area[fm["area"]].append((qid, fm))
    for area in AREA_ORDER:
        rows = by_area[area]
        if not rows:
            continue
        L.append(f"### {area} ({len(rows)})")
        L.append("")
        rows_by_status = {}
        for qid, fm in rows:
            rows_by_status.setdefault(fm["status"], []).append((qid, fm))
        ordered_statuses = [s for s in STATUS_ORDER if s in rows_by_status] + \
            [s for s in sorted(rows_by_status) if s not in STATUS_ORDER]
        for status in ordered_statuses:
            L.append(f"**{status}**")
            L.append("")
            for qid, fm in sorted(rows_by_status[status], key=lambda p: int(p[0][1:])):
                ties = ", ".join(fm["ties"]) if fm["ties"] else "—"
                L.append(f"- **[{qid} — {fm['title']}]({fm['_file']})** — {fm['description']}  ")
                L.append(f"  ties: {ties}")
            L.append("")

    # ── the tie-graph ──
    L.append("## Tie graph")
    L.append("")
    L.append("Nodes = questions (`Q<N> · slug`) + their tie targets (other questions, ADRs). An")
    L.append("edge `A --> B` reads \"A ties B\". Generated from the `ties:` frontmatter; a dangling")
    L.append("edge fails generation, so every arrow resolves to a real question or ADR.")
    L.append("")
    L.append("```mermaid")
    L.append("graph LR")
    emitted = set()

    def emit_node(link, cls):
        if link in emitted:
            return
        emitted.add(link)
        L.append(f'  {node_id(link)}["{target_label(link)}"]:::{cls}')

    for qid, fm in questions:
        emit_node(qid, "q")
    for qid, fm in questions:
        for t in fm["ties"]:
            emit_node(t, "adr" if t.startswith("ADR-") else "extq")
    for qid, fm in questions:
        for t in fm["ties"]:
            L.append(f"  {node_id(qid)} --> {node_id(t)}")
    L.append("  classDef q fill:#dbeafe,stroke:#2563eb,color:#1e3a8a;")
    L.append("  classDef extq fill:#eef2ff,stroke:#6366f1,color:#312e81;")
    L.append("  classDef adr fill:#f1f5f9,stroke:#64748b,color:#334155;")
    L.append("```")
    L.append("")
    return "\n".join(L)


def main():
    args = sys.argv[1:]
    questions = load_questions()
    if not questions:
        sys.exit("gen-questions-index: no Q*.md files in docs/notes/questions/.")
    ids = valid_ids(questions)

    # EDGE VALIDATION — the point of the whole thing.
    dangling = []
    for qid, fm in questions:
        for t in fm["ties"]:
            if t not in ids:
                dangling.append((qid, t))
    if dangling:
        print("── gen-questions-index (edge validation) ──")
        for qid, t in dangling:
            print(f"  DANGLING TIE: {qid} ties {t!r} — no such question or ADR.")
        sys.exit(1)

    content = render(questions, ids)

    if "--check" in args:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != content:
            print("── gen-questions-index ──")
            print("FAIL: docs/notes/questions/INDEX.md is stale — run `just questions-index`.")
            return 1
        status, msg = validate_mermaid(content)
        print(f"questions-index: OK — INDEX.md ≡ the question files. (mermaid: {status} — {msg})")
        return 1 if status == "fail" else 0

    # build: compile the mermaid before persisting — never write a broken graph
    status, msg = validate_mermaid(content)
    if status == "fail":
        print(f"── gen-questions-index ──\nFAIL: mermaid does not compile (NOT written):\n{msg}")
        return 1
    open(OUT, "w", encoding="utf-8").write(content)
    tail = "mermaid compiles ✓" if status == "pass" else f"(compile-check {status})"
    print(f"questions-index: wrote docs/notes/questions/INDEX.md ({len(questions)} questions). {tail}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
