#!/usr/bin/env python3
"""gen-gate-index.py — the gate composition, generated from the justfile (the root).

The quality gates are DEFINED in `justfile` recipes (`verify`/`fitness`); their
composition was hand-described in `.claude/codebase-maintenance.md`, which drifted
(said fitness = 4 checks when it ran 7; listed a gitleaks leg after it was removed).
This regenerates that description from the recipes — the gate's legs and what each
leg checks (glossed from each tool's own first doc-line, so the gloss is SSoT too).
Same move as `gen-adr-index.py` for the ADR ledger; `--check` fails on drift.

Zero dependencies (stdlib), like the other tools/ scripts.
"""
import os
import re
import sys

ROOT = os.path.abspath(os.environ.get("REFS_ROOT", "."))
JUSTFILE = os.path.join(ROOT, "justfile")
DOC = os.path.join(ROOT, ".claude/codebase-maintenance.md")
GEN_BEGIN = "<!-- BEGIN GENERATED gate-index (just gate-index) — do not hand-edit -->"
GEN_END = "<!-- END GENERATED gate-index -->"

# The gates we describe, in the order they fire, + the one-line role of each.
GATES = [
    ("fitness", "every commit (pre-commit hook) — the fast no-build bundle"),
    ("verify", "`.lean` commits + release — the full build gate"),
]

# Glosses for non-tool legs (recipe deps / builtins that have no tools/ doc-line).
BUILTIN = {
    "lake build": "compile the Lean library (the build gate)",
    "node tools/selfcheck.mjs": "third-impl row-unifier sanity (semilattice laws · unify_sound)",
}

# Role override for recipe-deps whose cmd expansion is noisy (multi-line / conditionals).
RECIPE_ROLE = {
    "build": "compile the Lean library (first run pulls Mathlib oleans)",
}


def parse_recipes(text):
    """name -> {'deps': [...], 'cmds': [raw command lines]}. Handles `name: dep1 dep2`."""
    recipes, cur = {}, None
    for line in text.splitlines():
        m = re.match(r"^([a-zA-Z][\w-]*)(?:\s+[A-Z][\w=\"]*)*\s*:(.*)$", line)
        if m and not line.startswith(" "):
            cur = m.group(1)
            deps = [d for d in m.group(2).strip().split() if d and not d.startswith("#")]
            recipes[cur] = {"deps": deps, "cmds": []}
        elif cur and (line.startswith("    ") or line.startswith("\t")):
            s = line.strip()
            if s and not s.startswith("#") and not s.startswith("@just"):
                recipes[cur]["cmds"].append(s.lstrip("@-"))
        elif line and not line.startswith(" "):
            cur = None
    return recipes


def tool_of(cmd):
    """Extract the tools/<file> path a command invokes, if any."""
    m = re.search(r"(tools/[\w./-]+\.(?:sh|py|mjs))", cmd)
    return m.group(1) if m else None


def gloss(cmd):
    """One-line description: from the tool's own first doc-line (`<tool> — <desc>`),
    else a builtin gloss, else the bare command."""
    t = tool_of(cmd)
    if t:
        path = os.path.join(ROOT, t)
        if os.path.exists(path):
            for ln in open(path, encoding="utf-8").read().splitlines()[:8]:
                ln = ln.lstrip("#").strip().lstrip('"').strip()
                if "—" in ln:                       # `<tool> — <desc>`
                    desc = ln.split("—", 1)[1].strip().rstrip(".")
                    # trim to first sentence/clause for compactness
                    return re.split(r"\.\s|\. $|;", desc)[0].strip()
    for k, g in BUILTIN.items():
        if k in cmd:
            return g
    return f"`{cmd}`"


def legs_of(name, recipes, seen=None):
    """Ordered (label, gloss) legs of a gate: expand recipe-deps one level, then own cmds."""
    seen = seen or set()
    out = []
    r = recipes.get(name, {"deps": [], "cmds": []})
    for dep in r["deps"]:
        if dep in recipes and dep not in seen:
            seen.add(dep)
            dr = recipes[dep]
            if dep in RECIPE_ROLE:                       # noisy expansion → one clean role
                out.append((dep, RECIPE_ROLE[dep]))
            elif dr["cmds"]:                             # gloss from the dep's primary command
                out.append((tool_of(dr["cmds"][0]) or dep, gloss(dr["cmds"][0])))
            else:
                out.append((dep, f"recipe `{dep}`"))
    for c in r["cmds"]:
        out.append((tool_of(c) or c, gloss(c)))
    return out


def render(recipes):
    lines = [GEN_BEGIN,
             "_Generated by `tools/gen-gate-index.py` from `justfile`. The gate legs + what "
             "each checks (glossed from each tool's own first doc-line)._", ""]
    for gate, role in GATES:
        lines.append(f"**`just {gate}`** — {role}:")
        lines.append("")
        for label, g in legs_of(gate, recipes):
            short = label.replace("tools/", "")
            lines.append(f"- `{short}` — {g}")
        lines.append("")
    lines.append(GEN_END.join([]) or GEN_END)
    # drop trailing blank before END
    while lines[-2] == "":
        lines.pop(-2)
    return "\n".join(lines)


def splice(md, block):
    return re.sub(re.escape(GEN_BEGIN) + r".*?" + re.escape(GEN_END), block, md, flags=re.DOTALL)


def main():
    check = "--check" in sys.argv
    recipes = parse_recipes(open(JUSTFILE, encoding="utf-8").read())
    block = render(recipes)
    md = open(DOC, encoding="utf-8").read()
    if GEN_BEGIN not in md or GEN_END not in md:
        print(f"gate-index: {DOC} has no GEN markers — add them to enable generation.", file=sys.stderr)
        return 1
    new = splice(md, block)
    if check:
        if new != md:
            print("── gate-index ──\nFAIL: .claude/codebase-maintenance.md gate block is stale "
                  "— run `just gate-index`.")
            return 1
        print("── gate-index ──\nPASS: gate composition block ≡ the justfile recipes.")
        return 0
    open(DOC, "w", encoding="utf-8").write(new)
    print(f"gate-index: regenerated the gate block in {os.path.relpath(DOC, ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
