#!/usr/bin/env python3
# tool: role=gen couples=Bang/**/*.lean,docs/notes/proof-assets.md,tools/leanlex.py runs-in=fitness
"""gen-proof-assets.py — generate the reusable-proof-assets inventory.

Single source of truth = the Lean sources; this note is a pure derivation
(the top rung of the derivation-strength ladder): it lists every
  * custom tactic / attribute definition (`macro`/`elab`/`syntax` producing
    tactics, `register_*_attr`),
  * `@[simp]`-tagged lemma, grouped by module (the de facto simp sets),
so "what reusable proof machinery exists?" is answered by a generated doc
that cannot drift. Regenerate with `just proof-assets`; `--check` diffs.
"""

from __future__ import annotations
import argparse
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

from leanlex import strip_comments

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "notes" / "proof-assets.md"

TACTIC_DEF = re.compile(
    r"^\s*(?:scoped\s+)?(macro|elab|syntax)\b(?=.*(?:: *tactic|: *attr|Tactic))",
)
REGISTER_ATTR = re.compile(r"register_\w+_attr")
SIMP_ATTR = re.compile(r"@\[[^\]]*\bsimp\b[^\]]*\]")
DECL_NAME = re.compile(
    r"^\s*(?:protected\s+|private\s+|noncomputable\s+|scoped\s+)*"
    r"(?:theorem|lemma|def|abbrev|instance)\s+([A-Za-z0-9_.'!?]+)"
)


def scan() -> tuple[list[str], dict[str, list[tuple[str, int]]]]:
    tactics: list[str] = []
    simps: dict[str, list[tuple[str, int]]] = defaultdict(list)
    for f in sorted((ROOT / "Bang").rglob("*.lean")):
        rel = f.relative_to(ROOT).as_posix()
        lines = strip_comments(f.read_text(encoding="utf-8")).splitlines()
        pending_simp = False
        for i, line in enumerate(lines, start=1):
            if TACTIC_DEF.search(line) or REGISTER_ATTR.search(line):
                tactics.append(f"`{rel}:{i}` — `{line.strip()[:90]}`")
            if SIMP_ATTR.search(line):
                # attr + decl on one line: strip the attribute(s) first
                m = DECL_NAME.match(re.sub(r"@\[[^\]]*\]\s*", "", line))
                if m:
                    simps[rel].append((m.group(1), i))
                else:
                    pending_simp = True
                continue
            if pending_simp:
                m = DECL_NAME.match(line)
                if m:
                    simps[rel].append((m.group(1), i))
                    pending_simp = False
                elif line.strip() and not line.lstrip().startswith("--"):
                    pending_simp = False  # attribute on something we don't inventory
    return tactics, simps


def render(tactics: list[str], simps: dict[str, list[tuple[str, int]]]) -> str:
    total = sum(len(v) for v in simps.values())
    lines = [
        "<!-- note-status: active -->",
        "<!-- GENERATED by tools/gen-proof-assets.py — do not hand-edit; run `just proof-assets` -->",
        "# Reusable proof assets (generated inventory)",
        "",
        "> The single source of truth is the Lean source; this page is a pure",
        "> derivation. What exists, where it lives, and what to reach for before",
        "> hand-rolling. Companion analysis: `just clones` (tools/clone-report.py)",
        "> ranks duplication for *future* extraction candidates; the triage of the",
        "> current families lives in docs/notes/clone-triage.md.",
        "",
        "## Custom tactics / attributes",
        "",
    ]
    if tactics:
        lines += [f"- {t}" for t in tactics]
    else:
        lines += [
            "**None.** There are no `macro`/`elab`/`syntax` tactic definitions and no",
            "registered attributes in `Bang/`. Reuse today = the simp sets below +",
            "template lemmas by convention (see the design notes for each spine, e.g.",
            "`krelS_state_reinstall` as the D5 template). The tactics-survey's",
            "`@[bang_grind]`/aesop recommendations remain unimplemented — see",
            "docs/notes/clone-triage.md for why the top clone families are not",
            "tactic-shaped.",
        ]
    lines += [
        "",
        f"## `@[simp]` sets by module ({total} lemmas)",
        "",
        "Calling `simp` in a module's proofs implicitly uses these; when writing",
        "new proofs in a module, check its set before re-proving a rewrite.",
        "",
    ]
    for rel in sorted(simps, key=lambda r: -len(simps[r])):
        entries = simps[rel]
        lines.append(f"### `{rel}` ({len(entries)})")
        lines.append("")
        for name, ln in entries:
            lines.append(f"- `{name}` ({rel.split('/')[-1]}:{ln})")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file differs from a fresh render")
    args = ap.parse_args()
    content = render(*scan())
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            print(f"STALE: {OUT.relative_to(ROOT)} — run `just proof-assets`",
                  file=sys.stderr)
            return 1
        print("proof-assets.md is fresh")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
