#!/usr/bin/env python3
# tool: role=gen couples=Bang/**/*.lean,docs/architecture/core-overview.md,genblock.py,import_facts.py runs-in=fitness
"""gen-import-graph.py — current BANG module graph from shared internal-import facts.
"""

import os
import re
import sys

from genblock import splice as _splice, validate_mermaid
from import_facts import ImportFacts, ImportFactsError, scan_bang

ROOT = os.path.abspath(os.environ.get("REFS_ROOT", "."))
DOC = os.path.join(ROOT, "docs/architecture/core-overview.md")
GEN_BEGIN = "<!-- BEGIN GENERATED import-graph (just import-graph) — do not hand-edit -->"
GEN_END = "<!-- END GENERATED import-graph -->"

TIER_ORDER = ["Frontend", "Core", "Backend", "Meta", "Witness", "Reify", "Apex"]
TIER_LABEL = {
    "Core": "Core — IR · typing · semantics · soundness",
    "Frontend": "Frontend — text → typed core",
    "Backend": "Backend — calculated machines → Wasm 3.0",
    "Meta": "Meta — contextual equivalence",
    "Witness": "Witness — executable evidence and counterexamples",
    "Reify": "Reify — calculated-machine proof laboratory",
    "Apex": "Apex — public theorem façade · audit · distribution",
}


def node_id(name: str) -> str:
    return name.replace("Bang.", "").replace(".", "_")


def render(facts: ImportFacts) -> str:
    fanin = {name: 0 for name in facts.modules}
    for _, imported in facts.edges:
        fanin[imported] += 1

    lines = [
        GEN_BEGIN,
        "_Generated by `tools/gen-import-graph.py` through `tools/import_facts.py` from current "
        "`import Bang.*` and `public import Bang.*` edges. Node label = `module (LOC · fan-in)`; "
        "an arrow `A → B` means A imports B._",
        "",
        "```mermaid",
        "graph TD",
    ]

    by_tier = {tier: [] for tier in TIER_ORDER}
    for fact in facts.modules.values():
        by_tier[fact.tier].append(fact)

    for tier in TIER_ORDER:
        members = sorted(by_tier[tier], key=lambda fact: fact.name)
        if not members:
            continue
        lines.append(f'  subgraph tier_{tier}["{TIER_LABEL[tier]}"]')
        for fact in members:
            lines.append(
                f'    {node_id(fact.name)}["{fact.short_name}<br/>{fact.loc}L · fan-in {fanin[fact.name]}"]'
            )
        lines.append("  end")

    for importer, imported in facts.edges:
        lines.append(f"  {node_id(importer)} --> {node_id(imported)}")
    lines.append("```")

    lines += ["", "| module | tier | LOC | fan-in |", "|---|---|---|---|"]
    ordered = sorted(facts.modules.values(), key=lambda fact: (-fanin[fact.name], fact.name))
    for fact in ordered:
        lines.append(f"| `{fact.short_name}` | {fact.tier} | {fact.loc} | {fanin[fact.name]} |")
    lines.append(GEN_END)
    return "\n".join(lines)


def splice(md: str, block: str) -> str:
    return _splice(md, GEN_BEGIN, GEN_END, block)


def main() -> int:
    try:
        __import__("subprocess").run(
            ["bash", os.path.join(os.path.dirname(__file__), "tool-log.sh"), os.path.basename(__file__)],
            check=False,
        )
    except Exception:
        pass

    args = sys.argv[1:]
    try:
        facts = scan_bang(ROOT)
    except ImportFactsError as exc:
        print(f"import-graph: FAIL — {exc}", file=sys.stderr)
        return 1
    block = render(facts)

    if not os.path.exists(DOC):
        print(f"import-graph: {DOC} missing", file=sys.stderr)
        return 1
    md = open(DOC, encoding="utf-8").read()
    if GEN_BEGIN not in md or GEN_END not in md:
        print(f"import-graph: {DOC} has no GEN markers — add them under §2 to enable.", file=sys.stderr)
        return 1

    if "--validate" in args:
        committed = re.search(re.escape(GEN_BEGIN) + r"(.*?)" + re.escape(GEN_END), md, re.DOTALL)
        status, msg = validate_mermaid(committed.group(1) if committed else "")
        print(f"── import-graph (mermaid compile) ──\n{status.upper()}: {msg}")
        return 1 if status == "fail" else 0

    new = splice(md, block)
    if "--check" in args:
        if new != md:
            print("── import-graph ──\nFAIL: core-overview.md §2 graph is stale — run `just import-graph`.")
            return 1
        print(f"── import-graph ──\nPASS: {len(facts.modules)} modules / {len(facts.edges)} import edges.")
        return 0

    status, msg = validate_mermaid(block)
    if status == "fail":
        print(f"── import-graph ──\nFAIL: generated mermaid does not compile (NOT written):\n{msg}")
        return 1
    open(DOC, "w", encoding="utf-8").write(new)
    suffix = "mermaid compiles ✓" if status == "pass" else f"compile-check {status}: {msg}"
    print(
        f"import-graph: regenerated §2 graph ({len(facts.modules)} modules, "
        f"{len(facts.edges)} edges; {suffix})."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
