#!/usr/bin/env python3
# tool: role=gen couples=examples/reactive-recomputation/Workload.bang,examples/reactive-observation-reuse/CachedWorkload.bang runs-in=fitness
"""Generate deterministic uncached and observation-scoped reactive workloads."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
UNCACHED_TARGET = ROOT / "examples" / "reactive-recomputation" / "Workload.bang"
CACHED_TARGET = ROOT / "examples" / "reactive-observation-reuse" / "CachedWorkload.bang"
LINE_COUNT = 100


def render() -> str:
    header = """-- Generated by tools/gen-reactive-workload.py; edit the generator, not this file.
-- A representative, deliberately uncached spreadsheet workload.
--
-- Every profiled formula returns (value, calls). Because the call count is part of the public result,
-- every supported evaluator must preserve the measurement. The 100 line items all share price and
-- quantity through one shared derived formula, then total fans the line items back in: 104 stable
-- declarations and 202 static dependency edges.

pub let price : Thunk (Int -> Int * Int) = {fun observed => (observed, 1)}

pub let quantity : Thunk (Int -> Int * Int) = {fun observed => (observed, 1)}

pub let unitAmount =
  {fun priceValue => fun quantityValue =>
    let priceMeasured = $price priceValue in
    let (p, priceCalls) = priceMeasured in
    let quantityMeasured = $quantity quantityValue in
    let (q, quantityCalls) = quantityMeasured in
    (p * q, 1 + priceCalls + quantityCalls)}

"""
    formulas = []
    for index in range(1, LINE_COUNT + 1):
        name = f"{index:03d}"
        formulas.append(
            f"""pub let line{name} =
  {{fun priceValue => fun quantityValue =>
    let measured = $unitAmount priceValue quantityValue in
    let (amount, calls) = measured in
    (amount + {index}, 1 + calls)}}
"""
        )

    bindings = []
    values = []
    calls = []
    for index in range(1, LINE_COUNT + 1):
        name = f"{index:03d}"
        bindings.extend(
            [
                f"    let measured{name} = $line{name} priceValue quantityValue in",
                f"    let (value{name}, calls{name}) = measured{name} in",
            ]
        )
        values.append(f"value{name}")
        calls.append(f"calls{name}")

    total = (
        "pub let total =\n"
        "  {fun priceValue => fun quantityValue =>\n"
        + "\n".join(bindings)
        + "\n    ("
        + " + ".join(values)
        + ",\n     1 + "
        + " + ".join(calls)
        + ")}\n"
    )
    return header + "\n".join(formulas) + "\n" + total


def render_cached() -> str:
    header = """-- Generated by tools/gen-reactive-workload.py; edit the generator, not this file.
-- The same 100-line DAG with one explicit observation-scoped Memo capability.

pub effect Memo {
  swap : Int -> Int
}

pub let price : Thunk (Int -> Int * Int) = {fun observed => (observed, 1)}

pub let quantity : Thunk (Int -> Int * Int) = {fun observed => (observed, 1)}

pub let unitAmount : Thunk (Cap Memo -> Int -> Int -> Int * Int ! {Memo}) =
  {fun memo => fun priceValue => fun quantityValue =>
    let hit = memo.swap(0) in
    if hit == 0
    then
      let priceMeasured = $price priceValue in
      let (p, priceCalls) = priceMeasured in
      let quantityMeasured = $quantity quantityValue in
      let (q, quantityCalls) = quantityMeasured in
      let computed = p * q in
      let stored = memo.swap(computed) in
      (computed, 1 + priceCalls + quantityCalls)
    else
      let restored = memo.swap(hit) in
      (hit, 1)}

"""
    formulas = []
    for index in range(1, LINE_COUNT + 1):
        name = f"{index:03d}"
        formulas.append(
            f"""pub let line{name} : Thunk (Cap Memo -> Int -> Int -> Int * Int ! {{Memo}}) =
  {{fun memo => fun priceValue => fun quantityValue =>
    let measured = $unitAmount memo priceValue quantityValue in
    let (amount, calls) = measured in
    (amount + {index}, 1 + calls)}}
"""
        )

    bindings = []
    values = []
    calls = []
    for index in range(1, LINE_COUNT + 1):
        name = f"{index:03d}"
        bindings.extend(
            [
                f"    let measured{name} = $line{name} memo priceValue quantityValue in",
                f"    let (value{name}, calls{name}) = measured{name} in",
            ]
        )
        values.append(f"value{name}")
        calls.append(f"calls{name}")

    total = (
        "pub let total : Thunk (Cap Memo -> Int -> Int -> Int * Int ! {Memo}) =\n"
        "  {fun memo => fun priceValue => fun quantityValue =>\n"
        + "\n".join(bindings)
        + "\n    ("
        + " + ".join(values)
        + ",\n     1 + "
        + " + ".join(calls)
        + ")}\n"
    )
    return header + "\n".join(formulas) + "\n" + total


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in workload differs from the generated source",
    )
    args = parser.parse_args()
    expected = {
        UNCACHED_TARGET: render(),
        CACHED_TARGET: render_cached(),
    }

    if args.check:
        stale = []
        for target, wanted in expected.items():
            actual = target.read_text() if target.exists() else ""
            if actual != wanted:
                stale.append(target.relative_to(ROOT))
        if stale:
            print("reactive-workload: STALE — regenerate " + ", ".join(map(str, stale)))
            return 1
        print(
            "reactive-workload: OK — uncached and observation-scoped workloads are current."
        )
        return 0

    for target, wanted in expected.items():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(wanted)
    print("reactive-workload: regenerated uncached and observation-scoped workloads.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
