#!/usr/bin/env python3
# tool: role=gen couples=CLAUDE.md,llms.txt runs-in=fitness
"""gen-llms-txt.py — generate llms.txt (the LLM-doc-index standard, llmstxt.org).

A CURATED, agent-friendly index at the repo root pointing an LLM at the key docs.
It is a pure DERIVATION of `CLAUDE.md` (SSoT) — the "What BANG is" summary + the
Reference-index table (which already IS the curated "what to read" list). Regenerate
with `just llms-txt`; `--check` gates it in `just fitness` (drift unrepresentable).

Fail-loud (sys.exit) if CLAUDE.md's expected markers move — same discipline as
gen-reference.py / gen-questions-index.py.

Usage:  gen-llms-txt.py          regenerate llms.txt
        gen-llms-txt.py --check  exit 1 if llms.txt != regenerated
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLAUDE = os.path.join(ROOT, "CLAUDE.md")
OUT = os.path.join(ROOT, "llms.txt")

# Always-loaded entry docs (the core is CLAUDE.md itself + CONTRIBUTING; they aren't
# rows in the reference table, so name them explicitly at the top).
ENTRY = [
    ("CLAUDE.md", "the always-loaded core — invariants (never break these) · glossary · architecture-in-force · the verify command"),
    ("CONTRIBUTING.md", "how to contribute (human or agent) — the workflow · where docs live (ADR-0077/0078) · agent write-discipline"),
]


def strip_md(s: str) -> str:
    s = re.sub(r"\*\*(.+?)\*\*", r"\1", s)   # **bold**
    s = s.replace("`", "")                     # `code`
    return s.strip()


def extract_summary(text: str) -> str:
    m = re.search(r"^## What BANG is\s*\n+(.+?)(?:\n\n|\n##)", text, re.S | re.M)
    if not m:
        sys.exit("gen-llms-txt: could not find the '## What BANG is' summary paragraph in CLAUDE.md.")
    para = " ".join(line.strip() for line in m.group(1).strip().splitlines())
    return strip_md(para)


def extract_reference_rows(text: str):
    m = re.search(r"^## Reference index\b.*?\n(\|.*?)(?:\n\n|\n##)", text, re.S | re.M)
    if not m:
        sys.exit("gen-llms-txt: could not find the '## Reference index' table in CLAUDE.md.")
    rows = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != 2:
            continue
        desc, target = cells
        if desc.lower().startswith("when you need") or set(desc) <= {"-", ":", " "}:
            continue  # header / separator
        rows.append((strip_md(desc), strip_md(target)))
    if not rows:
        sys.exit("gen-llms-txt: the Reference-index table parsed to zero rows — shape changed?")
    return rows


def render(text: str) -> str:
    summary = extract_summary(text)
    rows = extract_reference_rows(text)
    out = []
    out.append("<!-- generated by tools/gen-llms-txt.py from CLAUDE.md — do not hand-edit. `just llms-txt` -->")
    out.append("# bang-lang")
    out.append("")
    out.append(f"> {summary}")
    out.append("")
    out.append("Documentation is **git-native** and agent-readable by design (ADR-0078): every doc below is a "
               "file in this repository. This index is a generated view over `CLAUDE.md`'s reference index.")
    out.append("")
    out.append("## Start here")
    for path, desc in ENTRY:
        out.append(f"- [{path}]({path}): {desc}")
    out.append("")
    out.append("## Documentation")
    for desc, target in rows:
        # a reference row is `desc | target`; target may be a path, a glob (paths/PATH-*.md), or a command (`just`)
        is_file = ("/" in target or target.endswith(".md")) and "*" not in target
        link = f"[{target}]({target})" if is_file else f"`{target}`"
        out.append(f"- {link} — {desc}")
    out.append("")
    return "\n".join(out)


def main():
    check = "--check" in sys.argv
    text = open(CLAUDE, encoding="utf-8").read()
    generated = render(text)
    if check:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current.rstrip("\n") != generated.rstrip("\n"):
            sys.exit("llms.txt is STALE — run `just llms-txt` (llms.txt != generated from CLAUDE.md).")
        print("llms-txt: OK — llms.txt ≡ CLAUDE.md's reference index.")
    else:
        open(OUT, "w", encoding="utf-8").write(generated + "\n")
        print(f"llms-txt: wrote {OUT} ({len(generated.splitlines())} lines).")


if __name__ == "__main__":
    main()
