#!/usr/bin/env python3
# tool: role=gen couples=docs/notes/*.md,docs/notes/README.md runs-in=fitness
"""gen-notes-index.py — generate docs/notes/README.md, the notes map.

The GENERATE-rung twin of check-doc-hygiene's TEST rung. `docs/notes/` is a flat
folder of design notes; this renders an always-current index grouped by
`note-status` (active / archival / historical), each entry its H1 title. The map
cannot drift — it is a pure function of the notes + their frontmatter (the
ADR-ledger pattern applied to notes). CLAUDE.md keeps its curated topic pointers
for the ACTIVE set (the always-loaded working index); this is the exhaustive map
a reader consults on demand.

  gen-notes-index.py           # regenerate docs/notes/README.md
  gen-notes-index.py --check   # exit 1 if it is stale (for fitness)
"""
import os
import re
import sys
import subprocess

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True).stdout.strip()
NOTES = os.path.join(ROOT, "docs", "notes")
OUT = os.path.join(NOTES, "README.md")
STATUS_RE = re.compile(r"note-status:\s*(active|archival|historical)")

ORDER = ["active", "archival", "historical"]
BLURB = {
    "active": "Current living reference. Also pointed to by CLAUDE.md's reference index.",
    "archival": "Spike / experiment / pivot record — input to a specific ADR; preserved, not current.",
    "historical": "Pre-pivot narrative, honestly labelled; kept for the story, superseded by present docs.",
}


def h1(text):
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return "(no title)"


def render():
    groups = {s: [] for s in ORDER}
    unstamped = []
    for fn in sorted(os.listdir(NOTES)):
        if not fn.endswith(".md") or fn == "README.md":
            continue
        txt = open(os.path.join(NOTES, fn)).read()
        m = STATUS_RE.search(txt.split("\n", 1)[0])
        if not m:
            unstamped.append(fn)
            continue
        groups[m.group(1)].append((fn, h1(txt)))

    lines = ["# docs/notes — the design-notes map",
             "",
             "<!-- GENERATED by tools/gen-notes-index.py — do not hand-edit. "
             "Each note declares `<!-- note-status: … -->` on line 1. -->",
             "",
             "> The exhaustive index of `docs/notes/`, grouped by status. CLAUDE.md's reference",
             "> table carries the curated *active* pointers (the always-loaded working set); this",
             "> is the full map. Regenerate with `just notes-index`; `--check` gates it in `just fitness`.",
             ""]
    for s in ORDER:
        entries = groups[s]
        lines.append(f"## {s} ({len(entries)})")
        lines.append("")
        lines.append(f"_{BLURB[s]}_")
        lines.append("")
        for fn, title in entries:
            lines.append(f"- [`{fn}`]({fn}) — {title}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n", unstamped


def main():
    check = "--check" in sys.argv
    content, unstamped = render()
    if unstamped:
        print("── gen-notes-index ──")
        print("ERROR: notes missing a `note-status` frontmatter marker:")
        for fn in unstamped:
            print(f"    docs/notes/{fn}")
        return 1
    if check:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != content:
            print("── gen-notes-index ──")
            print("FAIL: docs/notes/README.md is stale — run `just notes-index`.")
            return 1
        print("notes-index: OK — docs/notes/README.md ≡ the notes + their status.")
        return 0
    open(OUT, "w").write(content)
    print("notes-index: regenerated docs/notes/README.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
