#!/usr/bin/env python3
# tool: role=gen couples=tools/*.sh,tools/*.py,tools/*.mjs,tools/README.md runs-in=fitness
"""gen-tools-index.py — generate tools/README.md, the tools map.

The GENERATE-rung twin of the header convention. `tools/` is a FLAT folder of ~45
scripts (renaming/foldering them would ripple through justfile/hooks/CI/ADR-evidence
links for cosmetic gain — so the layout stays flat and the legibility comes from a
generated map instead). Every script carries a machine-readable header line:

    # tool: role=<gen|check|lane|test|workflow> couples=<comma-list|none> runs-in=<fitness|verify|hook|manual|ci>

This parses those headers + each script's first prose comment and renders an
always-current table grouped by role. The map cannot drift — it is a pure function
of the scripts + their headers (the gen-notes-index / ADR-ledger pattern applied to
tools/). A script MISSING the header is a loud CHECK FAILURE naming the file — that
is what keeps future scripts on the convention.

  gen-tools-index.py           # regenerate tools/README.md
  gen-tools-index.py --check   # exit 1 if it is stale or a script lacks a header
"""
import os
import re
import subprocess
import sys

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True).stdout.strip()
TOOLS = os.path.join(ROOT, "tools")
OUT = os.path.join(TOOLS, "README.md")

HEADER_RE = re.compile(r"^(?:#|//)\s*tool:\s*"
                       r"role=(\S+)\s+couples=(\S+)\s+runs-in=(\S+)\s*$")

ROLE_ORDER = ["gen", "check", "test", "workflow", "lane"]
ROLE_BLURB = {
    "gen":      "Generators — write a derived artifact from a root (drift-unrepresentable). `--check` gates each in `just fitness`.",
    "check":    "Checks — fitness functions that fail on drift (structural invariants, doc/ref reachability, git-store safety).",
    "test":     "Tests — exercise a real boundary (the compiled `bang` binary, a live Wasmtime, the row-unifier) end-to-end.",
    "workflow": "Workflow — bootstrap / orientation / dev-loop helpers; not a gate.",
    "lane":     "Lane scripts — one-off orchestration helpers.",
}


def required_scripts():
    """Tracked tools/ scripts that MUST carry a header: *.py/*.sh/*.mjs + the
    extensionless git-hooks/pre-commit. Skips allow-list *.txt and asset dirs."""
    out = subprocess.run(["git", "ls-files", "tools/"], capture_output=True,
                         text=True, cwd=ROOT).stdout.splitlines()
    keep = []
    for f in out:
        if f.endswith((".py", ".sh", ".mjs")) or f == "tools/git-hooks/pre-commit":
            keep.append(f)
    return sorted(keep)


SEP_RE = re.compile(r"^\S+\s*(?:—|--)\s*")  # a leading `<name> — ` / `<name> -- ` prefix


def first_purpose(text):
    """One-line purpose: the first prose line AFTER the `# tool:` header, stripped of
    comment/docstring leaders and of a leading `<name> — ` / `<name> -- ` prefix if any.
    Reading past the header (not just line 0) is what makes the .mjs `//`-header and the
    shebang'd scripts glue up to the same first prose line."""
    lines = text.splitlines()
    past_header = False
    for line in lines[:14]:
        if HEADER_RE.match(line):
            past_header = True
            continue
        if not past_header:
            continue
        s = line.lstrip("#/").strip().lstrip('"').strip()
        if not s:
            continue
        s = SEP_RE.sub("", s, count=1)      # drop `<name> — ` prefix, keep the desc
        return s.rstrip(".")
    return "(no purpose comment)"


def parse(scripts):
    """(role, name, couples, runs_in, purpose) rows + the list of header-less files."""
    rows, missing = [], []
    for f in scripts:
        txt = open(os.path.join(ROOT, f), encoding="utf-8").read()
        hdr = None
        for line in txt.splitlines()[:6]:
            m = HEADER_RE.match(line)
            if m:
                hdr = m
                break
        if not hdr:
            missing.append(f)
            continue
        role, couples, runs_in = hdr.group(1), hdr.group(2), hdr.group(3)
        # name relative to tools/ so hook-subdir scripts read cleanly
        name = f[len("tools/"):]
        rows.append((role, name, couples, runs_in, first_purpose(txt)))
    return rows, missing


def render(rows):
    lines = ["# tools/ — the script map",
             "",
             "<!-- GENERATED by tools/gen-tools-index.py — do not hand-edit. "
             "Each script declares a `# tool: role=… couples=… runs-in=…` header; "
             "this table is a pure function of those headers. -->",
             "",
             "> The flat `tools/` folder, grouped by role. Regenerate with "
             "`just tools-index`; `--check` gates it (and the header convention) in "
             "`just fitness`. `couples` = the files/tools a script reads-from or "
             "writes-to; `runs-in` = where it fires (fitness · verify · hook · manual · ci).",
             ""]
    by_role = {}
    for row in rows:
        by_role.setdefault(row[0], []).append(row)
    seen_roles = list(ROLE_ORDER) + [r for r in by_role if r not in ROLE_ORDER]
    for role in seen_roles:
        entries = sorted(by_role.get(role, []), key=lambda r: r[1])
        if not entries:
            continue
        lines.append(f"## {role} ({len(entries)})")
        lines.append("")
        lines.append(f"_{ROLE_BLURB.get(role, '')}_")
        lines.append("")
        lines.append("| script | runs-in | couples-with | purpose |")
        lines.append("|---|---|---|---|")
        for _role, name, couples, runs_in, purpose in entries:
            couples_md = "—" if couples == "none" else f"`{couples.replace(',', '`, `')}`"
            lines.append(f"| [`{name}`]({name}) | `{runs_in}` | {couples_md} | {purpose} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    check = "--check" in sys.argv
    scripts = required_scripts()
    rows, missing = parse(scripts)
    if missing:
        print("── gen-tools-index ──")
        print("ERROR: tools/ scripts missing the `# tool: role=… couples=… runs-in=…` header:")
        for f in missing:
            print(f"    {f}")
        print("Add the header line near the top (after the shebang). Format:")
        print("    # tool: role=<gen|check|test|workflow|lane> couples=<comma-list|none> runs-in=<fitness|verify|hook|manual|ci>")
        return 1
    content = render(rows)
    if check:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != content:
            print("── gen-tools-index ──")
            print("FAIL: tools/README.md is stale — run `just tools-index`.")
            return 1
        print("tools-index: OK — tools/README.md ≡ the scripts + their headers.")
        return 0
    open(OUT, "w").write(content)
    print("tools-index: regenerated tools/README.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
