#!/usr/bin/env python3
# tool: role=gen couples=docfacts/architecture.json,docfacts/schema/architecture.schema.json,docs/architecture/core-overview.md,docfacts_architecture.py,genblock.py runs-in=fitness
"""Generate the current BANG module graph from serialized architecture facts."""

import json
import os
import re
import sys
from pathlib import Path

from docfacts_architecture import parse_fact
from genblock import marker_bounds, splice as _splice, validate_mermaid
from jsonschema.exceptions import ValidationError

ROOT = Path(os.environ.get("REFS_ROOT", ".")).resolve()
DOC = ROOT / "docs/architecture/core-overview.md"
FACT = ROOT / "docfacts/architecture.json"
GEN_BEGIN = (
    "<!-- BEGIN GENERATED import-graph (just import-graph) — do not hand-edit -->"
)
GEN_END = "<!-- END GENERATED import-graph -->"

TIER_ORDER = ["Frontend", "Core", "Backend", "Meta", "Witness", "Reify", "Apex"]
TIER_LABEL = {
    "Core": "Core — IR · typing · semantics · soundness",
    "Frontend": "Frontend — text → typed core",
    "Backend": "Backend — calculated machines → Wasm 3.0",
    "Meta": "Meta — contextual equivalence",
    "Witness": "Witness — executable evidence and counterexamples",
    "Reify": "Reify — calculated-machine proof laboratory",
    "Apex": "Apex — public theorem façade · audit · distribution",
}


def node_id(name: str) -> str:
    return "n_" + name.encode("utf-8").hex()


def short_name(name: str) -> str:
    return name.removeprefix("Bang.")


def import_edges(modules: list[dict]) -> list[tuple[str, str]]:
    return sorted(
        (module["name"], imported)
        for module in modules
        for imported in module["directImports"]
    )


def render(fact: dict) -> str:
    modules = {module["name"]: module for module in fact["modules"]}
    edges = import_edges(fact["modules"])
    fanin = {name: 0 for name in modules}
    for _, imported in edges:
        fanin[imported] += 1

    lines = [
        GEN_BEGIN,
        "_Generated by `tools/gen-import-graph.py` from validated "
        "`docfacts/architecture.json` module records. Node label = `module (LOC · fan-in)`; "
        "an arrow `A → B` means A imports B._",
        "",
        "```mermaid",
        "graph TD",
    ]

    by_tier = {tier: [] for tier in TIER_ORDER}
    for module in modules.values():
        by_tier[module["tier"]].append(module)

    for tier in TIER_ORDER:
        members = sorted(by_tier[tier], key=lambda module: module["name"])
        if not members:
            continue
        lines.append(f'  subgraph tier_{tier}["{TIER_LABEL[tier]}"]')
        for module in members:
            lines.append(
                f'    {node_id(module["name"])}["{short_name(module["name"])}<br/>'
                f'{module["loc"]}L · fan-in {fanin[module["name"]]}"]'
            )
        lines.append("  end")

    for importer, imported in edges:
        lines.append(f"  {node_id(importer)} --> {node_id(imported)}")
    lines.append("```")

    lines += ["", "| module | tier | LOC | fan-in |", "|---|---|---|---|"]
    ordered = sorted(
        modules.values(), key=lambda module: (-fanin[module["name"]], module["name"])
    )
    for module in ordered:
        lines.append(
            f"| `{short_name(module['name'])}` | {module['tier']} | "
            f"{module['loc']} | {fanin[module['name']]} |"
        )
    lines.append(GEN_END)
    return "\n".join(lines)


def splice(md: str, block: str) -> str:
    return _splice(md, GEN_BEGIN, GEN_END, block)


def load_fact() -> dict:
    if not FACT.is_file():
        raise OSError(f"{FACT} missing")
    return parse_fact(FACT.read_text(encoding="utf-8"))


def main() -> int:
    try:
        __import__("subprocess").run(
            ["bash", str(Path(__file__).with_name("tool-log.sh")), Path(__file__).name],
            check=False,
        )
    except Exception:
        pass

    args = sys.argv[1:]
    try:
        fact = load_fact()
        block = render(fact)
    except (
        OSError,
        json.JSONDecodeError,
        ValidationError,
        KeyError,
        ValueError,
    ) as exc:
        print(f"import-graph: FAIL — {exc}", file=sys.stderr)
        return 1

    if not DOC.exists():
        print(f"import-graph: {DOC} missing", file=sys.stderr)
        return 1
    md = DOC.read_text(encoding="utf-8")
    try:
        marker_bounds(md, GEN_BEGIN, GEN_END)
    except ValueError as exc:
        print(f"import-graph: FAIL — {exc}", file=sys.stderr)
        return 1

    if "--validate" in args:
        committed = re.search(
            re.escape(GEN_BEGIN) + r"(.*?)" + re.escape(GEN_END), md, re.DOTALL
        )
        status, msg = validate_mermaid(committed.group(1) if committed else "")
        print(f"── import-graph (mermaid compile) ──\n{status.upper()}: {msg}")
        return 1 if status == "fail" else 0

    new = splice(md, block)
    edges = import_edges(fact["modules"])
    if "--check" in args:
        if new != md:
            print(
                "── import-graph ──\nFAIL: core-overview.md §2 graph is stale — run `just import-graph`."
            )
            return 1
        print(
            f"── import-graph ──\nPASS: {len(fact['modules'])} modules / {len(edges)} import edges."
        )
        return 0

    status, msg = validate_mermaid(block)
    if status == "fail":
        print(
            f"── import-graph ──\nFAIL: generated mermaid does not compile (NOT written):\n{msg}"
        )
        return 1
    DOC.write_text(new, encoding="utf-8")
    suffix = (
        "mermaid compiles ✓" if status == "pass" else f"compile-check {status}: {msg}"
    )
    print(
        f"import-graph: regenerated §2 graph ({len(fact['modules'])} modules, "
        f"{len(edges)} edges; {suffix})."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
