#!/usr/bin/env python3
# tool: role=gen couples=examples/reactive-recomputation/Workload.bang runs-in=fitness
"""Generate the deterministic 100-line reactive recomputation workload."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "examples" / "reactive-recomputation" / "Workload.bang"
LINE_COUNT = 100


def render() -> str:
    header = """-- Generated by tools/gen-reactive-workload.py; edit the generator, not this file.
-- A representative, deliberately uncached spreadsheet workload.
--
-- Every profiled formula returns (value, calls). Because the call count is part of the public result,
-- every supported evaluator must preserve the measurement. The 100 line items all share price and
-- quantity through one shared derived formula, then total fans the line items back in: 104 stable
-- declarations and 202 static dependency edges.

pub let price : Thunk (Int -> Int * Int) = {fun observed => (observed, 1)}

pub let quantity : Thunk (Int -> Int * Int) = {fun observed => (observed, 1)}

pub let unitAmount =
  {fun priceValue => fun quantityValue =>
    let priceMeasured = $price priceValue in
    let (p, priceCalls) = priceMeasured in
    let quantityMeasured = $quantity quantityValue in
    let (q, quantityCalls) = quantityMeasured in
    (p * q, 1 + priceCalls + quantityCalls)}

"""
    formulas = []
    for index in range(1, LINE_COUNT + 1):
        name = f"{index:03d}"
        formulas.append(
            f"""pub let line{name} =
  {{fun priceValue => fun quantityValue =>
    let measured = $unitAmount priceValue quantityValue in
    let (amount, calls) = measured in
    (amount + {index}, 1 + calls)}}
"""
        )

    bindings = []
    values = []
    calls = []
    for index in range(1, LINE_COUNT + 1):
        name = f"{index:03d}"
        bindings.extend(
            [
                f"    let measured{name} = $line{name} priceValue quantityValue in",
                f"    let (value{name}, calls{name}) = measured{name} in",
            ]
        )
        values.append(f"value{name}")
        calls.append(f"calls{name}")

    total = (
        "pub let total =\n"
        "  {fun priceValue => fun quantityValue =>\n"
        + "\n".join(bindings)
        + "\n    ("
        + " + ".join(values)
        + ",\n     1 + "
        + " + ".join(calls)
        + ")}\n"
    )
    return header + "\n".join(formulas) + "\n" + total


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in workload differs from the generated source",
    )
    args = parser.parse_args()
    expected = render()

    if args.check:
        actual = TARGET.read_text() if TARGET.exists() else ""
        if actual != expected:
            print(f"reactive-workload: STALE — regenerate {TARGET.relative_to(ROOT)}")
            return 1
        print("reactive-workload: OK — 100-line generated workload is current.")
        return 0

    TARGET.write_text(expected)
    print(f"reactive-workload: regenerated {TARGET.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
